[Insights Management] Add `Customize your insights` card
wordpress-mobile/WordPress-iOS pull request #12261
Opened 2019-08-01 21:50 UTC by ScoutHarris

Fixes #12244 

To test:

---
TIP: If you'd like to force the Customize card to show without reinstalling the app: 
- In `SiteStatsInsightsTableViewController:loadInsightsFromUserDefaults`, set `hideCustomizeCard` to `false`.
- When you navigate away from Stats and back, the card will show.

---
- Go to Insights.
- Verify the customize card is displayed at the top.

<img width="400" alt="customize" src="https://user-images.githubusercontent.com/1816888/62329015-e94db980-b471-11e9-8d47-2b15fa60d695.png">

---
- Select 'Try it now'.
- Verify an alert is displayed (it's temporary, since the IM view doesn't exist yet).

<img width="300" alt="alert" src="https://user-images.githubusercontent.com/1816888/62329099-2a45ce00-b472-11e9-986d-85c51e9c20a6.png">

---
- Select 'Dismiss'.
- Verify the Customize card is dismissed.
  - NOTE: I banged my head for a while trying to animate that. I'll come back to it later.
- Verify the Customize card is not displayed again.
  - Navigate away from Stats and return.
  - Select another site.
  - Relaunch the app.

---
- Reinstall the app.
- Verify the Customize card is displayed.

---
- Disable the `statsInsightsManagement` feature flag.
- Verify the Customize card is not displayed.

---
Update release notes:

- [x] If there are user facing changes, I have added an item to `RELEASE-NOTES.txt`.

2019-08-01 21:55 UTC, ScoutHarris commented
@SylvesterWilmott - screenshots:

![iphone_portrait](https://user-images.githubusercontent.com/1816888/62329975-9fb29e00-b474-11e9-80db-0518fea879e5.png)

![ipad_portrait](https://user-images.githubusercontent.com/1816888/62329982-a4775200-b474-11e9-95bf-435467c67aa2.png)

![ipad_landscape](https://user-images.githubusercontent.com/1816888/62329994-a80ad900-b474-11e9-997d-ca8608dacb1e.png)

2019-08-02 06:05 UTC, SylvesterWilmott commented
This looks great!

Since you asked me if we could replace this image with a .pdf version, would it also be feasible to add a tablet version as well which would only show on iPads?

2019-08-02 13:21 UTC, danielebogo requested changes
Hey @ScoutHarris I left one tiny comment, other than that it looks good. I tested it and it worked perfectly. Also I saw this warning building the branch: `CustomizeInsightsCell.xib:w8p-Zf-FRY: warning: Automatically Adjusts Font requires using a Dynamic Type text style [9]`.

A part from these 2 small things everything is good to :shipit:

2019-08-02 13:21 UTC, danielebogo commented on WordPress/Classes/ViewRelated/Stats/Insights/Insights Management/CustomizeInsightsCell.swift
> +
You can remove the _weak_ here and make them private if you don't need to expose these properties.

2019-08-02 18:34 UTC, ScoutHarris commented
Hey @SylvesterWilmott .

> would it also be feasible to add a tablet version as well which would only show on iPads?

Yep, that's totally doable.

2019-08-02 18:45 UTC, ScoutHarris commented
Hey @danielebogo . Thanks for catching those issues. Both have been fixed. Ready for another review please.

2019-08-02 19:03 UTC, danielebogo approved these changes
LGTM! :shipit:

2019-08-02 19:40 UTC, merged