[iOS 13] Editor modals
wordpress-mobile/WordPress-iOS pull request #12378
Opened 2019-08-23 09:49 UTC by frosty

This PR updates the classic editor so that the blog picker, post settings, post preview, and media picker are displayed using iOS 13's new dismissable modal sheet style.

![editor-modals](https://user-images.githubusercontent.com/4780/63583044-1e8d8900-c592-11e9-983c-660091fa8c6a.gif)

I had to update one or two of the presented views to add a dismiss / done button. I also moved NoResultsViewController's dismiss button to the right side of the navigation bar for consistency.

**To test:**

* Build and run on iOS 13
* Start a new post in the classic editor (Aztec)
* Check each of the following are displayed in a modal sheet and can be dismissed:
    * Tap the blog picker in the navigation bar.
    * Tap `...` > Preview with no post content (no results view)
    * Tap `...` > Preview with post content
    * Tap `...` > Post Settings
    * Tap + in the formatting toolbar and open the media picker
* Also verify these are still presented 'normally' on iOS 12.

Update release notes:

- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

2019-08-23 13:31 UTC, iamthomasbishop commented
Wow, that was fast! Thanks for pulling this together so quickly! I just have one question:

Is it possible to achieve the "stacked cards" look, where the UI behind the modal sheet is scaled and moved down slightly, like so: 

<img width="538" alt="Screen Shot 2019-08-23 at 8 26 51 AM" src="https://user-images.githubusercontent.com/1200432/63596228-5d1a4800-c580-11e9-902e-372007030aee.png">

This isn't a blocker if we want to iterate, but it would be ideal if we could utilize that effect.

2019-08-23 13:54 UTC, danielebogo requested changes
LGTM! I left 3 comments about a `self` that can be removed. A part from that :shipit: 
It worked perfectly on iOS 12 and 13!

2019-08-23 13:54 UTC, danielebogo commented on WordPress/Classes/ViewRelated/Post/PostEditor+MoreOptions.swift
> +            self.navigationController?.pushViewController(settingsViewController, animated: true)
I think you can omit `self` here

2019-08-23 13:54 UTC, danielebogo commented on WordPress/Classes/ViewRelated/Post/PostEditor+MoreOptions.swift
> +            self.present(navigationController, animated: true)
I think you can omit `self` here too

2019-08-23 13:54 UTC, danielebogo commented on WordPress/Classes/ViewRelated/Post/PostEditor+MoreOptions.swift
> +            }
Here too

2019-08-28 09:08 UTC, frosty commented
@iamthomasbishop Please let me know how you'd like to proceed with this one, or if we should put it on hold for now :)

2019-10-07 13:35 UTC, loremattei commented
Hey! I'm moving this to 13.5 because 13.4 has been cut. If you want this PR to make it to 13.4, please feel free to move it back, target the release branch and ping me to build a new beta.

2019-10-21 10:56 UTC, loremattei commented
Hey! I'm moving this to 13.6 because 13.5 has been cut. If you want this PR to make it to 13.5, please feel free to move it back, target the release branch and ping me to build a new beta.

2019-11-07 13:00 UTC, frosty commented
I'm going to close this one for now as it's been open a long time. Will try to come back to it soon.

2019-11-07 13:00 UTC, closed without merging