Label changed from post settings to page settings
wordpress-mobile/WordPress-iOS pull request #14300
Opened 2020-06-11 19:13 UTC by negna1

Fixes #12374 

To test:

PR submission checklist:

- [ ] I have considered adding unit tests where possible.
- [ ] I have considered adding accessibility improvements for my changes.
- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

2020-06-12 11:38 UTC, frosty requested changes
Thank you for working on this issue!

Unfortunately, the changes you've made aren't exactly what was specified by the original issue. The intended fix should be that when editing a Post the menu item is named "Post Settings", and when editing a Page the menu item should be named "Page Settings". This PR changes the "Post Settings" menu item to be named "Page Settings" for both posts and pages. Would you be able to revise it?

2020-06-12 12:18 UTC, negna1 commented
> Thank you for working on this issue!
> 
> Unfortunately, the changes you've made aren't exactly what was specified by the original issue. The intended fix should be that when editing a Post the menu item is named "Post Settings", and when editing a Page the menu item should be named "Page Settings". This PR changes the "Post Settings" menu item to be named "Page Settings" for both posts and pages. Would you be able to revise it?

I got it. Yes I can revise it

2020-06-16 10:45 UTC, frosty requested changes

2020-06-16 10:45 UTC, frosty commented on WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift
> +        if let _ = post as? Post {
We could remove a little duplication here by initializing a string based on the post type

```
let settingsTitle = (post is Post) ? MoreSheetAlert.postSettingsTitle : MoreSheetAlert.pageSettingsTitle
alert.addDefaultActionWithTitle(settingsTitle) { [weak self] _ in
    self?.displayPostSettings()
}
```

2020-06-16 10:45 UTC, frosty commented on WordPress/Classes/ViewRelated/Gutenberg/GutenbergViewController+MoreActions.swift
> +        if let _ = post as? Post {
This could be done in the same way as the above comment.

2020-11-03 17:11 UTC, ScoutHarris commented
https://github.com/wordpress-mobile/WordPress-iOS/issues/12374 was fixed with https://github.com/wordpress-mobile/WordPress-iOS/pull/15207.

2020-11-03 17:11 UTC, closed without merging