Reader P2: Follow/Unfollow comments capability
wordpress-mobile/WordPress-iOS pull request #14721
Opened 2020-08-21 19:09 UTC by leandroalonso

Fixes #14574

Adds follow/unfollow comments capability in Reader.

## To test

- [ ] #14655
- [ ] #14656
- [ ] #14703

PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

2020-08-21 21:07 UTC, emilylaguna requested changes
Overall this looks good and works functionality wise 👍  

I tested on:

iPhone 11 Pro - 13.3
iPhone 5s - 11.4

I left some comments below, mostly some typos that I found. 

Let me know your thoughts?

2020-08-21 21:07 UTC, emilylaguna commented on WordPress/Classes/ViewRelated/Reader/ReaderCommentsViewController.m
> +    headerView.onFollowConverationClick = ^{
Small typo fix. 

```suggestion
    headerView.onFollowConversationClick = ^{
```

2020-08-21 21:07 UTC, emilylaguna commented on WordPress/Classes/ViewRelated/Reader/ReaderPostHeaderView.h
> +@property (nonatomic, copy) ReaderPostHeaderFollowingCallback onFollowConverationClick;
Small typo fix: 

```suggestion
@property (nonatomic, copy) ReaderPostHeaderFollowingCallback onFollowConversationClick;
```

2020-08-21 21:07 UTC, emilylaguna commented on WordPress/Classes/ViewRelated/Reader/ReaderPostHeaderView.m
> +        self.onFollowConverationClick();
Same typo as above
```suggestion
    if (self.onFollowConversationClick) {
        self.onFollowConversationClick();
```

2020-08-21 21:07 UTC, emilylaguna commented on WordPress/WordPressTest/FollowCommentsServiceTests.swift
> +    func testCanFollowConverationIfReaderTeamTopic() {
```suggestion
    func testCanFollowConversationIfReaderTeamTopic() {
```

2020-08-21 21:07 UTC, emilylaguna commented on WordPress/WordPressTest/FollowCommentsServiceTests.swift
> +    func testCanFollowConverationIfWPForTeams() {
```suggestion
    func testCanFollowConversationIfWPForTeams() {
```

2020-08-21 21:07 UTC, emilylaguna commented on WordPress/WordPressTest/FollowCommentsServiceTests.swift
> +    func testCannotFollowConveration() {
```suggestion
    func testCannotFollowConversation() {
```

2020-08-21 21:07 UTC, emilylaguna commented on WordPress/Classes/ViewRelated/Reader/WPStyleGuide+Reader.swift
> +        button.setTitle(selectedText, for: .selected)
I know this was done in the `applyReaderFollowButtonStyle` declaration above, but I don't think we should include strings in the style guide. IMO the style guide is for colors, images, and fonts. 

Thoughts?

2020-08-21 21:07 UTC, emilylaguna commented on WordPress/WordPressTest/FollowCommentsServiceTests.swift
> +        // Asert
```suggestion
        // Assert
```

2020-08-25 15:21 UTC, leandroalonso commented on WordPress/Classes/ViewRelated/Reader/WPStyleGuide+Reader.swift
> +        button.setTitle(selectedText, for: .selected)
Done in dc76de80eb6ddd04bfff19fc360baed7c26641a8

2020-08-25 17:37 UTC, emilylaguna approved these changes
🚢 !

2020-08-25 17:44 UTC, merged