White Bars II: Serif fonts
wordpress-mobile/WordPress-iOS pull request #14803
Opened 2020-08-31 11:50 UTC by frosty

Refs #14774.

This PR switches the navigation bars to use serif fonts. We use the system font on iOS 13+, and Noto on older versions. This needed some extra methods added to WordPress-Shared-iOS here.

![white-headers-ii](https://user-images.githubusercontent.com/4780/91716754-25c57a80-eb88-11ea-8bbb-73c88a078d9f.png)

**To test**

- Build and run
- Test on iOS 12 and 13.
- Do a smoke test of the app and verify that you see serif fonts for the navigation bar title throughout. In particular, also check the blog selector in the editor, and the header in reader detail views.

PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

2020-08-31 12:19 UTC, osullivanchris approved these changes
Need to get my hands on the build, but judging from the screenshot this looks great. New York is definitely looking nicer than Noto to my eyes, but that's expected and I'm not sure we can do much to improve Noto.

2020-08-31 22:08 UTC, Gio2018 requested changes
Hey @frosty ! I had a few code comments, but other than that saw the same issue of  #14797 on iPad iOS 12

2020-08-31 22:08 UTC, Gio2018 commented on WordPress/Classes/Services/PageLayoutService.swift
> +        api.GET(urlPath, parameters: nil, success: { (responseObject, _) in
I think that, since this is using a `Decodable` object, it should use the new `GETData` that I added to `WordPressKit`. I am going to open that PR by today

2020-08-31 22:08 UTC, Gio2018 commented on WordPress/Classes/Services/GutenbergLayouts.swift
> +public struct GutenbergLayout: Codable {
maybe just `Decodable` would suffice? Unless we need to encode the same for any reason, of course

2020-08-31 22:08 UTC, Gio2018 commented on WordPress/Classes/Services/PageLayoutService.swift
> +        let urlPath = "/wpcom/v2/sites/\(blogId)/block-layouts"
Do you think it would make sense to move the remote network calls to `WordPressKit`?

2020-08-31 22:08 UTC, Gio2018 commented on WordPress/Classes/Services/PageLayoutService.swift
> +        guard let data = try? JSONSerialization.data(withJSONObject: response) else {
see above, so we don't have do decode-encode-decode

2020-08-31 22:08 UTC, Gio2018 commented on WordPress/Classes/ViewRelated/Gutenberg/Layout Picker/GutenbergLayoutPickerViewController.swift
> +    private var isLoading: Bool = true {
Could be done in a separate PR, but I wonder if this could be handled using some sort of `enum State` with associated values, instead of a boolean (example: `ReaderTabItemsStore`, which also uses `WordPressFlux`). This way, we don't need to explicitly set the bool in every situation, and would have more control on the actual state. What do you think?

2020-09-01 07:43 UTC, frosty commented
Sorry @Gio2018, you shouldn't have had to review all that Gutenberg code here. I think I accidentally pulled develop into this branch instead of `feature/white-bars-i`, putting it ahead of the base branch. I'll clean it up now.

2020-09-02 12:26 UTC, frosty commented
@Gio2018 I cleaned up the commits in this PR. Once the changes in #14797 are approved, is this one good to go too?

2020-09-02 16:27 UTC, Gio2018 approved these changes
> @Gio2018 I cleaned up the commits in this PR. Once the changes in #14797 are approved, is this one good to go too?

Hey @frosty  yes! :shipit: !

2020-09-04 20:59 UTC, merged