UL&S Tracking: tracks dismissal of the Help screen.
wordpress-mobile/WordPress-iOS pull request #14820
Opened 2020-09-02 18:19 UTC by diegoreymendez

Adds missing tracking of the dismissal of the help dialogue during the sign in flows.

## Testing:

In your console in Xcode, filter by "Tracked: unified".

1. Pic one of the enabled flows (Site Address, Google, SIWA) to Sign In.
2. Once you see the Help button in the top right corner of any screen tap it.
3. When the help screen is up, tap "Close".

Make sure you see this event in Xcode's console:

🔵 Tracked: unified_login_interaction <click: dismiss, flow: login_site_address, source: default, step: help>

## PR submission checklist:

- [ ] I have considered adding unit tests where possible.
- [ ] I have considered adding accessibility improvements for my changes.
- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

2020-09-02 18:32 UTC, diegoreymendez commented
Hey folks, sorry I spotted something more that needs changing.  I'm moving this back to draft and submitting in a few.  Apologies!

2020-09-02 18:55 UTC, diegoreymendez commented
Re-checked and this is ready for review.

2020-09-02 21:41 UTC, diegoreymendez commented
@jkmassel - This also goes into 15.6.

2020-09-03 13:56 UTC, mindgraffiti requested changes
I don't think it's correct to fire both the old Tracks and new one. When I tap the "Help" button, it reports both:
```
🔵 Tracked: unified_login_step <flow: login_site_address, source: default, step: help>
2020-09-03 08:51:32:656 WordPress[9945:2620759] 🔵 Tracked: support_opened <>
```

2020-09-03 14:34 UTC, diegoreymendez commented
> I don't think it's correct to fire both the old Tracks and new one. When I tap the "Help" button, it reports both:

This PR doesn’t change that event, so I’d prefer if we could move forward with this PR and handle the reported issue in a separate PR.

But it's not just the scope: part of the reason why I’d like to handle that request separately is because I'm not sure it will be an easy change.  The support screen is shown from several places within the App.

2020-09-03 14:51 UTC, mindgraffiti approved these changes
Unblocking this PR because I don't think the Help screens are the most important parts of the UL&S tracks

2020-09-03 14:53 UTC, diegoreymendez commented
Thanks @mindgraffiti

2020-09-03 14:53 UTC, merged

2020-09-03 14:53 UTC, diegoreymendez commented
@jkmassel - First one is merged.