Reader Improvements Detail: Address design review feedback
wordpress-mobile/WordPress-iOS pull request #15072
Opened 2020-10-08 15:10 UTC by emilylaguna

Fixes #15052

### To test:
1. Launch the app
2. Tap on Reader Detail
3. Make sure the bottom toolbar icons are all the same color in light and dark modes 
4. Tap on a topic
5. Make sure the back button says back
4. Tap back
5. Tap back again to go back to the feed
5. Make sure the Search icon is not black

This does not add any options to the more menu which will need to be addressed in a future task. 

### PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

2020-10-08 18:30 UTC, leandroalonso requested changes
The described steps work like a charm!

Left 2 comments to improve the code.

2020-10-08 18:30 UTC, leandroalonso commented on WordPress/Classes/ViewRelated/Reader/Detail/ReaderDetailViewController.swift
> +    func show(title: String?) { }
If this method does nothing, why keep it?

2020-10-08 18:30 UTC, leandroalonso commented on WordPress/Classes/ViewRelated/Reader/Detail/Views/ReaderDetailCommentsView.swift
> +        if commentCount > 0 {
This is a little bit hard to read, you can either add multiple `else ifs` or use `switch`:

```
        switch commentCount {
        case let count where count == 1:
            format = Strings.commentFormat
        case let count where count > 0:
            format = Strings.commentFormatPlural
        default:
            format = Strings.noCommentFormat
        }
```

I guess this is one of the cases that writing less lines of code makes it hardto understand. :p

2020-10-09 19:28 UTC, mbshakti commented
Looking good and works as expected! Thank you for addressing Emily! 🙏

2020-10-13 21:43 UTC, yaelirub commented
Great work, @emilylaguna ! 
I followed the test steps and it works as described.

As noted in DM, I do see an issue with the header when going back from the topic feed : 
![RI_3](https://user-images.githubusercontent.com/1335657/95919428-678a3900-0d62-11eb-9d8d-56d3f9100f39.gif)

2020-10-13 21:44 UTC, yaelirub requested changes
Issue with header not animating when going back to view

2020-10-13 22:35 UTC, emilylaguna commented
> As noted in DM, I do see an issue with the header when going back from the topic feed :

Fixed in: https://github.com/wordpress-mobile/WordPress-iOS/pull/15072/commits/3de66fd58706c85bdbafb8be5ded670927f30c51

2020-10-14 00:39 UTC, yaelirub approved these changes
LGTM! 👏

2020-10-14 13:00 UTC, merged