Activity Log: Date filter
wordpress-mobile/WordPress-iOS pull request #15412
Opened 2020-11-30 19:05 UTC by leandroalonso

Part of #15192

Waiting for https://github.com/wordpress-mobile/WordPress-iOS/pull/15359

Adds the feature to filter activities by a date range.

<img src="https://user-images.githubusercontent.com/7040243/100652386-a2056080-3325-11eb-8a30-35a8f6c9484c.gif" width="300">

**The filter bar/chips design is not part of this task.**

### To test

#### Selecting a range

1. Open Activity Log
2. Tap "Date Range" at the top
3. Select two different dates
4. Check that the results match your selected dates

#### Calendar keeps the selected dates

1. Tap the dates you selected at the top
2. Check that the Calendar opens with your previously selection
3. Tap Cancel
4. Nothing happens

#### Removing the date filter

1. Tap the "X" button at the filter bar
2. Checks that the filtering is reset

#### No results

1. Tap "Date Range" at the top
2. Select a range date in December (or any other you're sure won't return results)
3. The screen should display an error message: "No matching events found."

#### Single date

1. Clear the filter
2. Open the calendar
3. Select a single date
4. Check that results are returned

PR submission checklist:

- [ ] I have considered adding unit tests where possible.
- [ ] I have considered adding accessibility improvements for my changes.
- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

2020-12-01 19:45 UTC, emilylaguna requested changes
Awesome, looking good. I hit a few issues when testing the filtering:

If I select single date, I expected to see results only for that date, but I am seeing results from other days as well:
<img src="https://user-images.githubusercontent.com/793774/100787360-82cc0900-33e1-11eb-945c-cb636c17b150.png" width="30%" />

If I select a date range in the past (ex: April 1st 2015 to April 7th 2015) it is not scrolled into view upon closing, then reopening the calendar.
<img src="https://user-images.githubusercontent.com/793774/100787959-6b415000-33e2-11eb-8b97-7e81e3b37b2e.gif" width="30%" />

If I select Nov 28th to Nov 30th I see results from Nov 27th, Nov 28th but nothing else. 
<img src="https://user-images.githubusercontent.com/793774/100788120-a774b080-33e2-11eb-8e66-830919681720.png" width="30%" />

If one of the selected dates is not from this year we should show the year for both the dates. 

<img width="313" alt="Screen Shot 2020-12-01 at 2 38 02 PM" src="https://user-images.githubusercontent.com/793774/100788251-d559f500-33e2-11eb-8b40-50e443df746c.png">


I suspect most of the issues can be resolved by including a time in the `after` `before` query fields which is what .com includes. 

`after=2015-11-07 05:00:00&before=2020-11-15 04:59:59`

2020-12-02 13:54 UTC, leandroalonso commented
@emilylaguna ready for another review. :)

2020-12-02 20:01 UTC, emilylaguna requested changes
Looking good! Made a couple of comments below. 

Also we discussed this but I'll mention it here as well, when rotating the device to/from landscape the view scrolls to the very first date so Dec 2000

2020-12-02 20:01 UTC, emilylaguna commented on WordPress/Classes/ViewRelated/Activity/ActivityListViewModel.swift
> +    }
Unfortunately this logic doesn't work if I select 2 dates from a different year.  Here's how I envisioned the logic working. 

Also a naming change suggestion. 
```suggestion
    private func shouldDisplayFullYear(with firstDate: Date?, and secondDate: Date?) -> Bool {
        guard let firstDate = firstDate, let secondDate = secondDate else {
            return false
        }

        let currentYear = Calendar.current.dateComponents([.year], from: Date()).year
        let firstYear = Calendar.current.dateComponents([.year], from: firstDate).year
        let secondYear = Calendar.current.dateComponents([.year], from: secondDate).year

        return firstYear != currentYear || secondYear != currentYear
    }
```

2020-12-02 20:01 UTC, emilylaguna commented on WordPress/Classes/ViewRelated/Activity/CalendarViewController.swift
> +    private func scrollToFirstSelectedDateOrToday() {
Thoughts?

```suggestion
    private func scrollToVisibleDate() {
```

2020-12-02 20:51 UTC, leandroalonso commented on WordPress/Classes/ViewRelated/Activity/ActivityListViewModel.swift
> +    }
Thanks for that! Done!

2020-12-02 20:51 UTC, leandroalonso commented on WordPress/Classes/ViewRelated/Activity/CalendarViewController.swift
> +    private func scrollToFirstSelectedDateOrToday() {
Renamed!

2020-12-02 20:52 UTC, emilylaguna approved these changes
🚢

2020-12-02 21:28 UTC, merged

2020-12-03 12:05 UTC, leandroalonso commented
> Also we discussed this but I'll mention it here as well, when rotating the device to/from landscape the view scrolls to the very first date so Dec 2000

I've added a task to check that again in #15192