Activity Log: filter bar design
wordpress-mobile/WordPress-iOS pull request #15468
Opened 2020-12-10 21:28 UTC by leandroalonso

Part of #15192

Adds filter bar design + few enhancements on the calendar.

![2020-12-10 18 26 04](https://user-images.githubusercontent.com/7040243/101831830-443afa80-3b15-11eb-9cc7-cd8e35bf427a.gif)

### To test

1. Open Activity Log
2. Play with date range and activity type filters :)

Please, test by:

1. Running it on iPad and iPhone
2. Light and dark mode

PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

2020-12-11 18:01 UTC, emilylaguna requested changes
Heya, looking good. I love the speed of the calendar now 👍 

<details>
 <summary>Do we need to show the scrollbars here?</summary>
<img src="https://user-images.githubusercontent.com/793774/101937608-1656c400-3bb0-11eb-8017-650ecb90f421.png" width="30%"/>
</details>

<details>
 <summary>RTL: I think the filter icon should be fully aligned to the right of the view</summary>
<img src="https://user-images.githubusercontent.com/793774/101938024-b57bbb80-3bb0-11eb-899a-42e2bc5c5295.png" width="30%"/>
</details>

<details>
 <summary>RTL: There are some overlapping issues</summary>
<img src="https://user-images.githubusercontent.com/793774/101937911-7ea5a580-3bb0-11eb-8ed6-19de55475e85.png" width="30%"/>
</details>

2020-12-11 18:01 UTC, emilylaguna commented on WordPress/Classes/ViewRelated/Activity/ActivityListViewController.swift
> +        WPStyleGuide.applyBorderStyle(separator)
This method is pretty messy. What do you think about doing something like:

```
        filterStackView.alignment = .center
        filterStackView.spacing = Constants.filterStackViewSpacing
        filterStackView.translatesAutoresizingMaskIntoConstraints = false

        let filterIcon = UIImageView(image: UIImage.gridicon(.filter))
        filterIcon.tintColor = .listIcon
        filterIcon.heightAnchor.constraint(equalToConstant: Constants.filterHeightAnchor).isActive = true

        filterStackView.addArrangedSubview(filterIcon)
        filterStackView.addArrangedSubview(dateFilterChip)
        filterStackView.addArrangedSubview(activityTypeFilterChip)

        let scrollView = UIScrollView()
        scrollView.canCancelContentTouches = true
        scrollView.addSubview(filterStackView)
        containerStackView.addArrangedSubview(scrollView)

        NSLayoutConstraint.activate([
            filterStackView.leftAnchor.constraint(equalTo: scrollView.leftAnchor, constant: Constants.filterBarHorizontalPadding),
            filterStackView.rightAnchor.constraint(equalTo: scrollView.rightAnchor, constant: Constants.filterBarHorizontalPadding),
            filterStackView.topAnchor.constraint(equalTo: scrollView.topAnchor, constant: Constants.filterBarVerticalPadding),
            filterStackView.bottomAnchor.constraint(equalTo: scrollView.bottomAnchor, constant: Constants.filterBarVerticalPadding),
            scrollView.heightAnchor.constraint(equalTo: filterStackView.heightAnchor, constant: 2 * Constants.filterBarVerticalPadding)
        ])

        setupDateFilter()
        setupActivityTypeFilter()

        let separator = UIView()
        separator.translatesAutoresizingMaskIntoConstraints = false
        scrollView.addSubview(separator)
        NSLayoutConstraint.activate([
            separator.bottomAnchor.constraint(equalTo: scrollView.bottomAnchor, constant: 16),
            separator.leftAnchor.constraint(equalTo: scrollView.leftAnchor),
            separator.widthAnchor.constraint(equalTo: scrollView.widthAnchor),
            separator.heightAnchor.constraint(equalToConstant: 1)
        ])
```

2020-12-11 20:54 UTC, osullivanchris commented
Very slick, great job. A couple of really nice touches. The smart reselection of dates is great (adapting the start/end date whichever I'm closer to). Loading state works well. Generally feels very polished.

Minor details to consider:
- its per design, but does the 'x' in the chip feel too heavy? Should we go with the grey we're using in icons?
- Should we have a shadow beneath the selected dates on scroll? I never love when things just disappear behind nothing in the ui :stuck_out_tongue:
- I noticed on landscape that when I selected one date, the layout for the date selection heading was off-center

I haven't gotten the build working on my iPad yet but thought I'd share these. If I notice anything on iPad I'll add it later.

2020-12-14 21:29 UTC, jkmassel commented
👋 Howdy! Today's the day we're cutting the `16.4` release.

Because of that, this PR will be bumped to `16.5`. If you need it to be part of `16.4`, please merge it into the `release/16.4` branch and DM me – I'll be happy to cut a new beta release!

2020-12-15 19:26 UTC, leandroalonso commented on WordPress/Classes/ViewRelated/Activity/ActivityListViewController.swift
> +        WPStyleGuide.applyBorderStyle(separator)
Done in f94c667c2885278562c7ab15209a0abd435f2f35

I also extracted the filter to its own file.

2020-12-15 19:28 UTC, leandroalonso commented
@emilylaguna @osullivanchris ready for another review!

2020-12-16 15:34 UTC, emilylaguna requested changes
Hey RTL is looking much better! I noticed a couple more things:

In LTR the bottom separator doesn't go all to the way to the end when scrolling:

<img width="406" alt="Screen Shot 2020-12-16 at 10 24 26 AM" src="https://user-images.githubusercontent.com/793774/102368985-76bb7c00-3f89-11eb-80a3-a9f8ffa3fc54.png">

In RTL there is no separator at all 🤔 
<img width="409" alt="Screen Shot 2020-12-16 at 10 26 12 AM" src="https://user-images.githubusercontent.com/793774/102369115-9488e100-3f89-11eb-9fc2-449c48a6042e.png">

2020-12-16 17:37 UTC, leandroalonso commented
@emilylaguna fixed in cedc3b153b4a559dc5d4f62c862b955279b42111

2020-12-16 21:36 UTC, emilylaguna approved these changes
👏 Nice, working very well now.

2020-12-17 12:56 UTC, merged

2020-12-17 16:31 UTC, osullivanchris commented
> @emilylaguna @osullivanchris ready for another review!

All looks great now

- 'x' on the chip works better slightly lighter
- really nice job on the fade-out behind the calendar. Looks slick
- landscape centring issue fixed
- scrollbar hidden, looks much better

Noting you have a kinda animation going I think when the chip changes. I wasn't expecting it, but I think I like it. 

Have not been able to view directly on iPad, but looks good based on screenshots.

Big 👍  from me.