Merges the latest from the Large Headers feature branch into develop.
wordpress-mobile/WordPress-iOS pull request #15751
Opened 2021-02-01 14:22 UTC by diegoreymendez

Title has it.

What's important in this PR is to test the App with the feature flag `newNavigationBar` OFF, and make sure everything works fine.

Once this is merged, we can incrementally implement and push what remains to be done for `newNavigationBar` ON.

## Testing

- Make sure the UI in the My Site tab works fine.
- Make sure the Me button works fine.
- Make sure logging in and out between account with multiple sites, one site, and no sites works fine.

## PR submission checklist:

- [ ] I have considered adding unit tests where possible.
- [ ] I have considered adding accessibility improvements for my changes.
- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

2021-02-08 21:34 UTC, jkmassel commented
👋 We're freezing `16.7` today, so this PR is being bumped to `16.8`. If you need this to be part of the `16.7` release, please merge it into the `release/16.7` branch and DM me – I'll be happy to cut a new beta release!

2021-02-22 20:19 UTC, jkmassel commented
👋 We're freezing `16.8` today, so this PR is being bumped to `16.9`. If you need this to be part of the `16.8` release, please merge it into the `release/16.8` branch and DM me – I'll be happy to cut a new beta release!

2021-03-04 19:32 UTC, frosty requested changes
I have more to finish reviewing tomorrow, but here are the things I've picked up for now. I've seen some situations where there's no detail view (in My Sites) or no primary view (in Notifications):

|    |  |
| ------------- | ------------- |
| ![IMG_0575](https://user-images.githubusercontent.com/4780/110019020-db33df00-7d1f-11eb-9fba-428154c09a85.PNG) | ![IMG_0572](https://user-images.githubusercontent.com/4780/110019037-df5ffc80-7d1f-11eb-8525-b61528ca05c9.PNG) |

Also, with the feature flag disabled, the View Site web view header colours aren't correct – the title and buttons are invisible.

With the feature flag enabled, the Reader detail web view is broken too – again, no title or buttons.

![IMG_0051](https://user-images.githubusercontent.com/4780/110019396-4f6e8280-7d20-11eb-99e9-65d08da3fad1.PNG)

Finally, saw a small issue where the Jetpack header wasn't positioned correctly:

![IMG_0574](https://user-images.githubusercontent.com/4780/110019402-52697300-7d20-11eb-84e4-61abf39b73b0.PNG)

I'm going to start to work on the blockers tomorrow, and add everything else to the master issue to tackle next week.

2021-03-04 19:32 UTC, frosty commented on WordPress/Classes/Extensions/UIViewController+SiteCreation.swift
> +extension UIViewController {
Not sure why this has changed, as it's only used from `BlogListViewController`...

2021-03-04 19:32 UTC, frosty commented on WordPress/Classes/System/WindowManager.swift
> +        WPTabBarController.recreateSharedInstance()
Unsure quite why this is necessary. It seems like we have some retain cycles, as this keeps the old tab bar (and numerous other objects) in memory:

<img width="219" alt="image" src="https://user-images.githubusercontent.com/4780/109981720-153dba80-7cf9-11eb-9e86-820cdac6c12a.png">

2021-03-04 19:32 UTC, frosty commented on WordPress/Classes/ViewRelated/Blog/Blog Details/BlogDetailsViewController.m
> +    BlogDetailsViewController *viewController = [[BlogDetailsViewController alloc] initWithMeScenePresenter:[MeScenePresenter new]];
I think this method should ideally return an existing VC if one exists? We could check the root view controller of the navigation controller when the feature flag is enabled, otherwise use the old logic?

2021-03-04 19:32 UTC, frosty commented on WordPress/Classes/ViewRelated/Blog/Blog Details/BlogDetailsViewController.m
> +        [self switchToBlog:blog];
Might want weakSelf here.

2021-03-04 19:32 UTC, frosty commented on WordPress/Classes/ViewRelated/Blog/Blog Details/Detail Header/NewBlogDetailHeaderView.swift
> +        //titleButton.setTitle(title, for: .normal)
We can remove this

2021-03-04 19:32 UTC, frosty commented on WordPress/Classes/ViewRelated/Blog/Blog Details/Detail Header/NewBlogDetailHeaderView.swift
> +        //titleView.axis = .vertical
Check if these are still needed

2021-03-04 19:32 UTC, frosty commented on WordPress/Classes/ViewRelated/Blog/Blog List/BlogListViewController.m
> +        self.dataSource.showsDisclosureIndicator = NO;
This doesn't seem to be working for me at the moment.

2021-03-04 19:32 UTC, frosty commented on WordPress/Classes/ViewRelated/Blog/Blog List/BlogListViewController.m
> +        self.canBypassBlogList = false;
I don't think we want to toggle this to prevent it, if it's possible 🤔  That's a change from the previous behaviour.

2021-03-04 19:32 UTC, frosty commented on WordPress/Classes/ViewRelated/Blog/Blog List/BlogListViewController.m
> +    NSIndexPath* indexPath = [NSIndexPath indexPathForRow:0 inSection:0];
Double check that the performSelector is no longer required.

2021-03-04 19:32 UTC, frosty commented on WordPress/Classes/ViewRelated/Blog/Blog List/BlogListViewController.m
> +        if (self.blogSelected != nil) {
Maybe switch this to a `guard`

2021-03-04 19:32 UTC, frosty commented on WordPress/Classes/ViewRelated/Blog/Blog List/BlogListViewController.m
> -        if (![self splitViewControllerIsHorizontallyCompact]) {
I think we may need to re-add this, as I'm occasionally seeing an empty detail view on iPad:

![IMG_0572](https://user-images.githubusercontent.com/4780/110018731-855f3700-7d1f-11eb-8162-3b5c6c4a5fc8.PNG)

2021-03-04 23:46 UTC, Gio2018 requested changes
A few things that I noticed on iPhone 12 Pro Max (both simulator and device):

- My site, rotating to landscape, the detail view is empty:
- In landscape, site icon and quick actions buttons exceed the safe area

<p align=center>
<img width=400 src=https://user-images.githubusercontent.com/34376330/110045808-d9165400-7d10-11eb-96d1-8fbbcc9a67a2.png>
</p>

- My site/details (e.g. Stats): rotating to landscape leaves the detail empty and puts the view at the root of the split vc

<p align=center>
<img width=400 src=https://user-images.githubusercontent.com/34376330/110046255-50e47e80-7d11-11eb-859f-6b1897acd33e.PNG>
</p>

- still in landscape, the site picker auto-dismisses itself

<p align=center>
<img width=400 src=https://user-images.githubusercontent.com/34376330/110046373-825d4a00-7d11-11eb-8273-c5405130610a.gif>
</p>

2021-03-04 23:46 UTC, Gio2018 commented on WordPress/Classes/Models/Blog.m
> +    if (self.managedObjectContext == nil) {
Not against a safety check, but is there a situation where the managed context of a managed object would be nil?

2021-03-04 23:46 UTC, Gio2018 commented on WordPress/Classes/System/WindowManager.swift
> +        WPTabBarController.recreateSharedInstance()
+1

2021-03-08 18:22 UTC, jkmassel commented
👋 We've pushed this out of a couple of releases now, so I'm moving this over to the `someday` milestone

2021-03-16 11:51 UTC, frosty commented
I think that the core changes from this PR have now all been brought into develop via a set of other PRs, so I'm going to close it out.

2021-03-16 11:51 UTC, closed without merging