Add the Kanvas editor for creating a story
wordpress-mobile/WordPress-iOS pull request #15903
Opened 2021-02-17 07:36 UTC by bjtitus

Adds the Kanvas editor for Story creation, does not hook up editing or other advanced functionality.

### Testing

* Open to the Blog Detail page
* Tap the FAB
* Select the "Story post" option
* Ensure that the Kanvas Editor shows up and basic photo, video, and media import options work.
* Hit the blue confirm button from the edit screen.
* Confirm that the Prepublishing sheet is shown.

Note that publishing will _NOT_ work with these changes. This is focused on pulling in Kanvas and properly displaying the interfaces.

https://user-images.githubusercontent.com/3250/108170984-15627700-70b8-11eb-969d-8921250fed9b.mp4

PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

2021-02-17 17:03 UTC, danielebogo requested changes
Hey @bjtitus everything seems working fine.
I left one nit and I have one doubt only. If I'm wrong let me know and I will approve it immediately.

Another thing: if I dismiss the Prepublishing sheet the loading overview is still loading. Not sure if this is related to `Note that publishing will NOT work with these changes. ` Just in case it is not, I'll leave a video here:

https://user-images.githubusercontent.com/912252/108239473-daa52100-7141-11eb-93df-d99d760961e7.mp4

2021-02-17 17:03 UTC, danielebogo commented on WordPress/Classes/Services/Stories/CameraHandler.swift
> +    let createdMedia: ([Result<KanvasMedia?, Error>]) -> Void
Nit: what do you think to define `[Result<KanvasMedia?, Error>]` via `typealias`? I see it's used in different places.

2021-02-17 17:03 UTC, danielebogo commented on WordPress/Classes/Services/Stories/StoryEditor.swift
> +        let saveDirectory = try! FileManager.default.url(for: .documentDirectory, in: .userDomainMask, appropriateFor: nil, create: false)
Not sure, but since in WP we don't allow force unwrap (am I right?), shouldn't we avoid `try!` too?

2021-02-18 01:19 UTC, bjtitus commented
Thanks @danielebogo!

All of your feedback should be addressed.

> if I dismiss the Prepublishing sheet the loading overview is still loading.

This should be fixed by the changes in `7f573fa`.

2021-02-18 09:47 UTC, danielebogo approved these changes
LGTM! :shipit:

2021-02-18 17:09 UTC, merged