Add Button to Milestone Notifications detail view
wordpress-mobile/WordPress-iOS pull request #15956
Opened 2021-02-22 20:27 UTC by frosty

This PR adds the ability for notifications to show a button in their detail view. Notification text blocks with a `meta` value of `"button": true` will be assigned the `button` kind, and rendered using the new `NoteBlockButtonTableViewCell`.

<img src="https://user-images.githubusercontent.com/4780/108764100-0feaae00-754a-11eb-8747-f6b3f7f644cd.PNG" width=300>

**Note**

The button currently takes you to the notifications day view for the specified site, but our system for routing those deep links currently doesn't respect the date range passed to it. We'll tweak that in a future PR.

**To test**

- You'll need to have the backend diff for Milestone Notifications applied to your sandbox and your simulator or device set up to use this for API calls.
- Ensure you have a Milestone Notification present in your notifications list.
- Enable the milestone notifications feature flag.
- Build and run and view the notification. Check that the **Take a deep dive button** is present.
- Check other notifications, and ensure that the button doesn't show up elsewhere.
- Ensure tests pass.
- Ensure that the button doesn't show up if the feature flag is disabled.

PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

2021-02-22 20:59 UTC, yaelirub commented on WordPress/Classes/ViewRelated/Notifications/Views/NoteBlockButtonTableViewCell.swift
> +//  NoteBlockButtonTableViewCell.swift
I think you forgot to remove these?

2021-02-22 21:05 UTC, emilylaguna requested changes
Heya, this is working with the new notification. I left a few comments below.

When in dark mode there's a light background on the button section:

<img src="https://user-images.githubusercontent.com/793774/108768983-62b26e80-7526-11eb-9331-249914a5d19c.png" width="300" />

2021-02-22 21:05 UTC, emilylaguna commented on WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationDetailsViewController.swift
> +                }
When I tap on the button there's like a half a second lag, then the app switches tabs, and then pushes to the stats view. 

What do you think about Reusing the `self.displayURL(url)` from the other actions which then just pushes to the stats view in the notifications tab?

2021-02-22 21:05 UTC, emilylaguna commented on WordPress/Classes/ViewRelated/Notifications/Views/NoteBlockButtonTableViewCell.swift
> +
```suggestion
```

2021-02-22 21:05 UTC, emilylaguna commented on WordPress/Classes/ViewRelated/Notifications/FormattableContent/NotificationTextContent.swift
> +            return .button
What do you think about adding a `isViewMilestone` check here? I'm not 100% the button meta flag is exclusive to our notification.

2021-02-22 21:33 UTC, frosty commented on WordPress/Classes/ViewRelated/Notifications/Views/NoteBlockButtonTableViewCell.swift
> +//  NoteBlockButtonTableViewCell.swift
D'oh, thank you! 🙂

2021-02-22 21:34 UTC, frosty commented on WordPress/Classes/ViewRelated/Notifications/FormattableContent/NotificationTextContent.swift
> +            return .button
Sure!

2021-02-23 10:45 UTC, frosty commented on WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationDetailsViewController.swift
> +                }
Thanks, great suggestion! This seems to work really well – just looks like we'll need to tweak it to handle the date range 👍

2021-02-23 17:12 UTC, frosty commented
@emilylaguna Ready for another look! 👀

2021-02-23 18:50 UTC, emilylaguna approved these changes
Nice work! 🚀

2021-02-23 20:58 UTC, Gio2018 requested changes
This looks really good @frosty !!
A minor comment that can safely be ignored in the code, and one issue that I found:

- There seems to be a strange "persistence" of the stats between My Site and Notifications. See the video below: the site selected in "My site" is different than the one of the notification


https://user-images.githubusercontent.com/34376330/108907188-678b2700-75e7-11eb-9717-bbed875619f7.mp4

2021-02-23 20:58 UTC, Gio2018 commented on WordPress/Classes/Models/Notifications/Notification.swift
> +        return FeatureFlag.milestoneNotifications.enabled && type == "view_milestone"
nit: `return` is redundant, if you wish.

2021-02-23 22:44 UTC, frosty commented on WordPress/Classes/Models/Notifications/Notification.swift
> +        return FeatureFlag.milestoneNotifications.enabled && type == "view_milestone"
Hmm, I was kind of matching the style of the other one-line computed vars here – are you okay if we leave as-is?

2021-02-23 22:45 UTC, Gio2018 approved these changes

2021-02-24 10:34 UTC, merged