Improve appearance of Reader Detail when used in Notifications
wordpress-mobile/WordPress-iOS pull request #15995
Opened 2021-03-01 21:43 UTC by frosty

This PR makes a number of small (temporary!) changes to `ReaderDetailViewController` when used within the Notifications section of the app to improve consistency while we're still using blue navigation bars. It also fixes a few issues.

**Change 1: Back Button**

The back button was always shown, but when you view a notification in an expanded split view there's nowhere to go back to. The back button is now only displayed if the ReaderDetailVC isn't the first VC in its navigation controller's stack.

----

**Change 2: No Results View position**

I noticed on the iPad that if a post errored out, the no results view wasn't always in the right position. With this change, it should be fixed in the center of the view:

| Before  | After  |
|:-:|:-:|
|  ![Simulator Screen Shot - iPad Pro (9 7-inch) - 2021-03-01 at 20 39 30](https://user-images.githubusercontent.com/4780/109558940-f0b3c980-7ad1-11eb-8688-cdd7481509e8.png) | ![Simulator Screen Shot - iPad Pro (9 7-inch) - 2021-03-01 at 15 04 34](https://user-images.githubusercontent.com/4780/109558955-f6111400-7ad1-11eb-980c-fff789604544.png)  |

----

**Change 3: Bar colours**

The bar and its icons have been updated to match the rest of Notifications. I've added a slightly hacky `useCompatibilityMode` flag to achieve this for now, replacing some colours or disabling functionality in a few places. This should be easy to clean up when we ship white headers throughout the app, however.

I also disabled the Featured Image display as part of these changes as it's intended to work with a clear / white

| Before  | After  |
|:-:|:-:|
|  ![Simulator Screen Shot - iPad Pro (9 7-inch) - 2021-03-01 at 20 39 16](https://user-images.githubusercontent.com/4780/109560011-518fd180-7ad3-11eb-9f89-c45f91522fab.png)  |  ![Simulator Screen Shot - iPad Pro (9 7-inch) - 2021-03-01 at 19 09 02](https://user-images.githubusercontent.com/4780/109559947-3d4bd480-7ad3-11eb-9736-a2fa37a96c80.png)  |
|  ![Simulator Screen Shot - iPad Pro (9 7-inch) - 2021-03-01 at 21 28 26](https://user-images.githubusercontent.com/4780/109561456-18f0f780-7ad5-11eb-8881-648f8233ef31.png)  |  ![Simulator Screen Shot - iPad Pro (9 7-inch) - 2021-03-01 at 19 27 10](https://user-images.githubusercontent.com/4780/109559968-42108880-7ad3-11eb-94d0-7b1406f4428d.png)  |
|  ![Simulator Screen Shot - iPhone 12 Pro - 2021-03-01 at 20 37 04](https://user-images.githubusercontent.com/4780/109560093-610f1a80-7ad3-11eb-87f4-017a10811085.png)  | ![Simulator Screen Shot - iPhone 12 Pro - 2021-03-01 at 16 41 59](https://user-images.githubusercontent.com/4780/109560078-5eacc080-7ad3-11eb-9c10-bfa716645611.png)   |

----

**To test:**

- Ensure that the `newNavBarAppearance` feature flag is disabled.
- Build and run.
- In Notifications, navigate into any New Post notifications you may have and ensure they look as above.
- Check that a post with a featured image looks okay.
- From a comment or like notification, navigate into a post by tapping on the top item in the list, and ensure that the Reader view looks correct and has a back button.
- Check the navigation bar also looks good in dark mode.
- In Reader, navigate into some articles and check that the navigation bar is still white and looks the same. Check that posts with featured images look awesome.
- For extra credit, on iPad open another app in multitasking so that the split view is collapsed. Then in Notifications, navigate into a new post and check that you see the back button. Then remove multitasking and check that the back button goes away when the split view is expanded again.

PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

2021-03-01 22:10 UTC, emilylaguna requested changes
Nice workaround for this. Tested on iPhone and iPad and it all worked well. I did notice this small margin issue with the topics collection view:

<img width="200" alt="Screen Shot 2021-03-01 at 5 09 44 PM" src="https://user-images.githubusercontent.com/793774/109565782-f6e57e00-7ab0-11eb-93a0-13fabe40ee07.png">

2021-03-02 13:09 UTC, frosty commented
Thanks @emilylaguna! I saw this issue while working on it, then fixed the issue, then reverted my change and then could never recreate the issue again so I assumed it was caused by something else. I'll take another look 👍

2021-03-02 16:40 UTC, emilylaguna approved these changes
Yay, confirmed your fix works.

<img width="409" alt="Screen Shot 2021-03-02 at 11 39 08 AM" src="https://user-images.githubusercontent.com/793774/109681918-f0581480-7b4b-11eb-8e21-5ad91b2d1415.png">

2021-03-02 16:45 UTC, frosty commented
Thank you!

2021-03-02 17:23 UTC, merged