Feature/15356 invite link
wordpress-mobile/WordPress-iOS pull request #16005
Opened 2021-03-03 15:17 UTC by aerych

Refs #15356 

This PR wires up the UI for the Invite Links feature.

To test:

PR submission checklist:

- [ ] I have considered adding unit tests where possible.
- [ ] I have considered adding accessibility improvements for my changes.
- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

2021-03-03 22:32 UTC, aerych commented
cc @mattmiklic for a design check :)

2021-03-03 23:13 UTC, ScoutHarris requested changes
Hey Eric.

It all looks good except for one thing. The Message footer is now blue, and is a link to the roles definition. 

<img width="490" alt="message_footer" src="https://user-images.githubusercontent.com/1816888/109885227-62f3ed80-7c3b-11eb-881d-4fc1fac66f05.png">

2021-03-03 23:13 UTC, ScoutHarris commented on WordPress/Classes/ViewRelated/People/InvitePersonViewController.swift
> +            break
Couldn't `default` cover these?

2021-03-04 15:54 UTC, aerych commented on WordPress/Classes/ViewRelated/People/InvitePersonViewController.swift
> +            break
Why yes. Yes it could. 👍

2021-03-04 17:50 UTC, mattmiklic requested changes
@aerych This looks good for the most part, but the "Generate new link" and "Share invite link" buttons are a shade of blue I don't recognize. Could you double-check that they're using our `primary` blue (blue 50 from Color Studio)?

2021-03-04 18:29 UTC, aerych commented
Thanks @ScoutHarris and @mattmiklic!  
I've updated the colors to be sure they are the correct ones. Please confirm :) 
The message section footer should no longer look or behave like a link.
I've cleaned up the switch statement. 

Ready for another peek!

![Simulator Screen Shot - iPhone 11 Pro - 2021-03-04 at 12 28 19](https://user-images.githubusercontent.com/1435271/110011593-3e545000-7ce5-11eb-8edb-f35792832b66.png)

2021-03-04 19:02 UTC, mattmiklic approved these changes
Looks good to me now!

2021-03-04 19:42 UTC, ScoutHarris approved these changes
👍 !

:shipit:

2021-03-04 20:01 UTC, aerych commented
Thank you all!!!

2021-03-04 20:01 UTC, merged