Add Notifications screen for unified prologue carousel
wordpress-mobile/WordPress-iOS pull request #16177
Opened 2021-03-29 09:46 UTC by frosty

Ref #15056. This PR adds the Notifications screen to the prologue carousel.

| iPhone | iPad |
|---|---|
| ![Simulator Screen Shot - iPhone 12 Pro - 2021-03-29 at 10 37 37](https://user-images.githubusercontent.com/4780/112818083-0e496400-907b-11eb-8ad3-32d1bc1c3d94.png) | ![Simulator Screen Shot - iPad Pro (9 7-inch) - 2021-03-29 at 10 41 30](https://user-images.githubusercontent.com/4780/112818640-a9423e00-907b-11eb-9742-6648d5ade817.png) |

**To test**

* Build, run and log out if necessary
* Verify that the notifications (third) page of the login prologue is consistent with the designs (see issue #15056; see also example screenshot below)

PR submission checklist:

- [x] I have considered adding unit tests where possible.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

2021-03-29 20:36 UTC, Gio2018 requested changes
Hey @frosty , as discussed on Slack, there's a crash happening, likely due to `NSAttributedString` not being called from the main thread. Other than that, I left a code comment.

2021-03-29 20:36 UTC, Gio2018 commented on WordPress/WordPress.xcodeproj/project.pbxproj
> +				1788106E260E488B00A98BD8 /* UnifiedPrologueNotificationsContentView.swift */,
we should probably move this file in a separate group or, if we feel that we have too many sub-groups, just remove the topic level (e.g. `Editor`).

2021-03-30 13:24 UTC, frosty commented
@Gio2018 Thanks for catching this! It turns out that the NSAttributedString construction from HTML needs to be run on the main thread, but there's no guarantee that SwiftUI will call it there. I've gone for a simpler approach to avoid having to use this at all. Let me know what you think.

2021-03-30 13:43 UTC, frosty commented on WordPress/WordPress.xcodeproj/project.pbxproj
> +				1788106E260E488B00A98BD8 /* UnifiedPrologueNotificationsContentView.swift */,
Good catch – I'll wait until this is merged to address this as I don't want to distrupt any other PRs.

2021-03-30 15:46 UTC, Gio2018 approved these changes
Works great now!

A few minor comments comparing to the designs:

- the "reply" icon should be bigger and moved a bit to the right
- the "star" icon maybe moved just a bit lower and a bit to the right
- the comments icon maybe moved a bit to the left

All these are of course super minor and can be safely ignored.

2021-03-30 20:50 UTC, merged