Reader: avoid duplicate requests
wordpress-mobile/WordPress-iOS pull request #16499
Opened 2021-05-14 14:42 UTC by leandroalonso

Fixes #16466

After many changes on the Reader, I realized that:

* Requests are being made twice
* We were recreating `ReaderStreamViewController` over and over

This PR changes how `ReaderStreamViewController` is instantiated withing the Reader section, thus:

* Fixing the two requests issue and the aforementioned #16466
* Makes Reader way faster

To test:

Make sure you're following any list.

1. Keep Charles (or any other request interception tool opened)
2. Open Reader
3. Go to your list
4. Make sure no duplicated requests are made to retrieve posts for this list
5. Play around and make sure the functionality is still the same

## Regression Notes
1. Potential unintended areas of impact
n/a

2. What I did to test those areas of impact (or what existing automated tests I relied on)
Manual testing.

3. What automated tests I added (or what prevented me from doing so)
I haven't. The overall code in Reader needs a lot of refactoring in order to be able to include automated tests. :(

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

2021-05-14 19:31 UTC, emilylaguna requested changes
While this does fix the duplicate requests, I encountered a few new bugs:

- I can't reproduce this reliably but a few times the view displays a failed message after loading

- When relaunches the app the discover loads then displays the empty view

https://user-images.githubusercontent.com/793774/118319209-71c31000-b4c8-11eb-9ed1-6d5e9d05482d.mov


I'm not sure what the repercussions are of switching to a reusable view controller (which I agree is the right move), I think we'll need to test this extensively before releasing.

2021-05-31 20:19 UTC, jkmassel commented
We're cutting `17.5` today, so this PR is being bumped to `17.6`

2021-06-08 13:58 UTC, leandroalonso commented
Hey @Gio2018, can I get your review on this one since touches some code you wrote? Thanks!

2021-06-09 19:47 UTC, Gio2018 reviewed
Hey @leandroalonso , this seems to solve the duplicate calls. when testing, I noticed the same issue mentioned by @emilylaguna: when the app restarts (specifically restoring the state from Reader/Discover) I see the content for a split second and then the no result VC is shown. BUT..
I then re-instated the `didTapResetFilterButton()` call and still saw the same issue. Can you please confirm that you see the issue in both cases? If so, I think it's safe to merge and open another issue for the no results. I also agree to have a reusable VC (which, if I remember correctly, was the way this was setup initially?)

2021-06-10 13:53 UTC, leandroalonso commented
@Gio2018 I see a somewhat different issue: no result VC is shown; then the content appears:

<img src="https://user-images.githubusercontent.com/7040243/121536394-64bb1300-c9d9-11eb-9c09-933f87389615.gif" width="300">

This is probably another issue, due to:

1. Discover posts are clean when the app starts
2. This causes this behavior if the app restores showing Discover

I created the issue here: https://github.com/wordpress-mobile/WordPress-iOS/issues/16663

2021-06-10 20:35 UTC, Gio2018 approved these changes

2021-06-10 20:41 UTC, emilylaguna approved these changes

2021-06-10 20:43 UTC, merged