Blogging reminders: format summary text at end of flow
wordpress-mobile/WordPress-iOS pull request #16708
Opened 2021-06-18 18:36 UTC by frosty

This PR formats the summary text at the end of the reminders flow. It shows a count of the days added along with a formatted list of the days.

| No days selected | One day selected | Multiple days (US) | Multiple days (UK) |
| --- | --- | --- | --- |
| ![Simulator Screen Shot - iPhone 12 Pro - 2021-06-18 at 19 26 37](https://user-images.githubusercontent.com/4780/122603310-0a225680-d06c-11eb-8d3d-ef678f652636.png) | ![Simulator Screen Shot - iPhone 12 Pro - 2021-06-18 at 19 26 27](https://user-images.githubusercontent.com/4780/122603314-0c84b080-d06c-11eb-82cc-60a46053874f.png) | ![Simulator Screen Shot - iPhone 12 Pro - 2021-06-18 at 19 26 47](https://user-images.githubusercontent.com/4780/122603325-127a9180-d06c-11eb-9872-86a8a68a01c8.png) | ![Simulator Screen Shot - iPhone 12 Pro - 2021-06-18 at 19 28 01](https://user-images.githubusercontent.com/4780/122603331-13abbe80-d06c-11eb-91d5-30f86fdf45e3.png) |

**To test**

### No days selected

- Run through the flow and select no days. Check that the prompt tells you you selected no days.

### One day selected

- Run through the flow and select no days. Check that the prompt tells you you will be reminded **once**, and lists the correct day.

### Multiple days selected (sunday first)

- Set your simulator's region to US
- Run through the flow and select multiple days. Check that the prompt tells you the correct count, and lists the days properly formatted and in the correct order starting with Sunday.

### Multiple days selected (monday first, the correct way 😅 )

- Set your simulator's region to UK
- Run through the flow and select multiple days. Check that the prompt tells you the correct count, and lists the days properly formatted and in the correct order starting with Monday.

## Regression Notes
1. Potential unintended areas of impact

None

2. What I did to test those areas of impact (or what existing automated tests I relied on)
3. What automated tests I added (or what prevented me from doing so)

N/A

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

2021-06-18 21:51 UTC, Gio2018 requested changes
Hey @frosty , I had one small code comment, but other than that, the summary font color needs to be fixed in dark mode (see screenshot)
<p align=center>
<img width="250" src="https://user-images.githubusercontent.com/34376330/122619155-69c13780-d055-11eb-9ede-d1d446922404.png">
</p>

2021-06-18 21:51 UTC, Gio2018 commented on WordPress/Classes/ViewRelated/Blog/Blogging Reminders/BloggingRemindersFlowCompletionViewController.swift
> +        style.lineSpacing = 1.5
can this number go in the `Metrics` enum?

2021-06-21 08:53 UTC, osullivanchris commented
Looks great @frosty . Just one thing. You have mentioned defining S-S or M-S based on UK/US region. But in site settings the user can actually customise this format. Would the logic here respect the customised setting? Maybe US/UK is just the name for that setting I'm not sure

2021-06-21 10:52 UTC, frosty commented
Thanks @Gio2018! I've addressed both of these items now, ready for another look.

@osullivanchris Thanks for raising this, I didn't realise that option was there! I think sticking with the device settings is probably the best option for now though, as that's where the user will be receiving notifications. It could be that their site is in a different country or timezone, so the settings may not be right to apply to the user's reminders.

2021-06-21 10:52 UTC, frosty commented
Thanks @Gio2018! I've addressed both of these items now, ready for another look.

@osullivanchris Thanks for raising this, I didn't realise that option was there! I think sticking with the device settings is probably the best option for now though, as that's where the user will be receiving notifications. It could be that their site is in a different country or timezone, so the settings may not be right to apply to the user's reminders.

2021-06-21 14:15 UTC, osullivanchris commented
> @osullivanchris Thanks for raising this, I didn't realise that option was there! I think sticking with the device settings is probably the best option for now though, as that's where the user will be receiving notifications. It could be that their site is in a different country or timezone, so the settings may not be right to apply to the user's reminders.

Oh cool. Good point too. I hadn't considered that in Weekly Roundup, where I was thinking we'd lead on site settings too. But if we can get this info from the device that seems strong, you're right.

2021-06-21 15:57 UTC, Gio2018 approved these changes

2021-06-21 15:57 UTC, merged

2021-06-21 16:04 UTC, diegoreymendez reviewed
Works perfectly.

2021-06-21 16:04 UTC, diegoreymendez commented on WordPress/Classes/Extensions/NSCalendar+Helpers.swift
> +    public func localizedDayIndex(_ index: Int) -> Int {
I still think this isn't very reusable - but since this was moved to an extension I think we should document what it does.  It would suffice to have a description so that the reader can quickly figure out if it does what they need.

I tried documenting it to make a suggestion here for you:

```
/// Maps a zero-based index number that represents the ordered day of the week,
/// to a localized index that can be used to access day information from calendar properties
/// such as `shortWeekdaySymbols`.
```

But honestly I'm not sure that's clear / easy to follow.