Removes some unnecessary conditions for presenting blogging reminders after posting.
wordpress-mobile/WordPress-iOS pull request #16830
Opened 2021-07-08 16:49 UTC by diegoreymendez

Removes some unnecessary conditions for presenting blogging reminders after posting.

We don't need to know that a post was published - it should be enough to know the user's intent to publish to present blogging reminders.

## To test:

1. Go to a site where blogging reminders hasn't been shown yet.
2. Publish a post.
3. Make sure blogging reminders is shown.

## Regression Notes

1. Potential unintended areas of impact

None.

2. What I did to test those areas of impact (or what existing automated tests I relied on)
3. What automated tests I added (or what prevented me from doing so)

PR submission checklist:

- [ ] I have completed the Regression Notes.
- [ ] I have considered adding unit tests for my changes.
- [ ] I have considered adding accessibility improvements for my changes.
- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

2021-07-08 16:50 UTC, diegoreymendez commented
Fyi @mokagio

2021-07-08 19:01 UTC, Gio2018 requested changes
Hey @diegoreymendez , I tested on iPhone 11 Pro Max iOS 14.6 and iPad Pro 2nd Gen 14.4.2 (both real devices) and the blogging reminders flow did not appear after publishing (I deleted the app before install to make sure no `UserDefaults` were saved)

2021-07-08 19:02 UTC, guarani reviewed
Noting that I'm still seeing the issue here on the iPad.

2021-07-08 20:31 UTC, diegoreymendez commented
Unfortunately, the PR caused some issues that require some extra though.  Together with @giorush we decided the current situation is better than risking to break something in 17.7.  I'm closing for now, and we'll work on this for 17.8.

2021-07-08 20:31 UTC, closed without merging

2021-07-09 03:04 UTC, mokagio commented
> Together with @giorush we decided the current situation is better than risking to break something in 17.7. 

Thanks for the thoughtfulness and for leaving the context here 🙌