Issue/17194 update domains dashboard after purchase
wordpress-mobile/WordPress-iOS pull request #17222
Opened 2021-09-27 10:31 UTC by diegoreymendez

Fixes #

To test:

## Regression Notes
1. Potential unintended areas of impact

2. What I did to test those areas of impact (or what existing automated tests I relied on)

3. What automated tests I added (or what prevented me from doing so)

PR submission checklist:

- [ ] I have completed the Regression Notes.
- [ ] I have considered adding unit tests for my changes.
- [ ] I have considered adding accessibility improvements for my changes.
- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

2021-09-29 14:02 UTC, diegoreymendez commented on WordPress/Classes/Services/BlogService+Domains.swift
> +extension BlogService {
This was added to make it possible to use `DomainService` without making `DomainService` a class (it's currently a struct), and making it inherit from `NSObject` and be declared as `@objc`.

Not sure this is the best call but I'm hoping we can discard this when `BlogService` is moved to Swift.

2021-09-29 14:02 UTC, diegoreymendez commented on WordPress/Classes/Services/BlogService.m
> +    dispatch_group_enter(syncGroup);
This block refreshed domains for a blog when the blog is fully synchronized.

2021-09-30 11:04 UTC, frosty requested changes
This generally seems to be working well for me, just left a few minor comments!

Tests 1 and 2 were successful, but I wasn't able to complete test 3 because the purchase webview gets dismissed as soon as it begins loading. I also receive an auth notification to the WordPress app which is installed on my other phone, so I guess it's auth related. I'm also not certain it's directly related to this PR.

2021-09-30 11:04 UTC, frosty commented on WordPress/Classes/Services/BlogService+Domains.swift
> +extension BlogService {
I think Swift extensions are fine to avoid having to make other Swift code obj-c compatible 🙂

2021-09-30 11:04 UTC, frosty commented on WordPress/Classes/Services/BlogService+Domains.swift
> +import Combine
Nitpick, can we remove the Combine reference here?

2021-09-30 11:04 UTC, frosty commented on WordPress/Classes/ViewRelated/Domains/Domain registration/RegisterDomainDetails/ViewModel/RegisterDomainDetailsServiceProxy.swift
> +    /// This method should not be called directly.  It's only meant to be used when a domain purchase is performed through
This comment says that this method shouldn't be called directly, but it's used by the above method? Is that okay?

2021-09-30 11:04 UTC, frosty commented on WordPress/Classes/ViewRelated/Domains/Domain registration/RegisterDomainSuggestions/DomainSuggestionViewControllerWrapper.swift
> +            /*
Can this commented out code be removed?

2021-09-30 15:07 UTC, diegoreymendez commented
I haven't been able to reproduce the issues with the web view's authentication yet, but I did address all other review comments.

2021-10-01 19:09 UTC, diegoreymendez commented
This is ready for review again.

2021-10-04 01:25 UTC, mokagio commented
@diegoreymendez  I'm going to bump this to the next release because we'll be code freezing 18.4 today and this hasn't been approved yet.

If this cannot wait two weeks and it's important that it makes it into this release, let me know and we'll organize a new beta once ready.

2021-10-04 15:25 UTC, frosty approved these changes
The PR itself and the changes look good 👍 I'm still having the auth issue with step 3, but I don't believe it's tied to this PR and I don't think it should hold up it being merged.

2021-10-05 10:26 UTC, merged