Makes the domain searches immediate.
wordpress-mobile/WordPress-iOS pull request #17266
Opened 2021-10-05 21:33 UTC by diegoreymendez

TBD.

This is a work in progress.

## To test:

## Regression Notes

1. Potential unintended areas of impact
2. What I did to test those areas of impact (or what existing automated tests I relied on)
3. What automated tests I added (or what prevented me from doing so)

PR submission checklist:

- [ ] I have completed the Regression Notes.
- [ ] I have considered adding unit tests for my changes.
- [ ] I have considered adding accessibility improvements for my changes.
- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

2021-10-05 22:22 UTC, Gio2018 approved these changes
Worked as expected!

2021-10-06 08:47 UTC, frosty requested changes
Changes work as expected, however the HUD gets lower down the screen each time a search is performed:

![domains-3](https://user-images.githubusercontent.com/4780/136170402-315d4a78-30e2-453a-9b35-a1120f775eb9.gif)

2021-10-06 14:34 UTC, diegoreymendez commented
@frosty - Ready for another look.

2021-10-06 15:11 UTC, frosty approved these changes
Works for me! One minor suggestion, both otherwise :shipit:

2021-10-06 15:11 UTC, frosty commented on WordPress/Classes/ViewRelated/NUX/DomainSuggestionsTableViewController.swift
>              SVProgressHUD.dismiss()
Nitpick, but we could extract a few of these things into a method we call from within the success and failure blocks (dismissing the hud, removing the background view, ending refreshing.

2021-10-06 16:36 UTC, diegoreymendez commented on WordPress/Classes/ViewRelated/NUX/DomainSuggestionsTableViewController.swift
>              SVProgressHUD.dismiss()
I'll submit another PR since it turned out to have a lot of space for improvement.

2021-10-06 16:51 UTC, diegoreymendez commented on WordPress/Classes/ViewRelated/NUX/DomainSuggestionsTableViewController.swift
>              SVProgressHUD.dismiss()
New PR with the proposed improvements here: https://github.com/wordpress-mobile/WordPress-iOS/pull/17272

2021-10-06 16:54 UTC, frosty commented on WordPress/Classes/ViewRelated/NUX/DomainSuggestionsTableViewController.swift
>              SVProgressHUD.dismiss()
👍

2021-10-06 18:36 UTC, merged