Unified About: Allow customizing row accessories and separators
wordpress-mobile/WordPress-iOS pull request #17431
Opened 2021-11-05 16:01 UTC by frosty

Fixes #17406. This PR updates the appearance of the rows in the Unified About screen, allowing them to display disclosure indicators as necessary. It also hides the separator beneath the Automattic Family row, to match the designs.

<img src="https://user-images.githubusercontent.com/4780/140540949-86d31b9d-62b5-4c25-b373-0df5be92a21b.png" width="350">

**To test**

- Build and run, and verify the screen matches the designs / above screenshot

## Regression Notes

1. Potential unintended areas of impact

None

2. What I did to test those areas of impact (or what existing automated tests I relied on)
3. What automated tests I added (or what prevented me from doing so)

N/A

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

2021-11-15 02:39 UTC, mokagio commented
@frosty  I'm going to bump this to the next release because we'll be code freezing 18.7 today and this hasn't been reviewed yet.

If this cannot wait two weeks and it's important that it makes it into this release, let me know and we'll organize a new beta once ready.

2021-11-16 12:27 UTC, diegoreymendez requested changes
The code looks fine, and the cells look also fine in portrait mode, but in landscape (iPhone) I'm seeing some strange misalignment on the left side of our cells.

<img width=300 src="https://user-images.githubusercontent.com/1836005/141982371-6f875510-af10-4e34-8059-40f0e9d5cddb.png">

It seems to only affect newly shown rows, so if you don't see the same, try scrolling the table view up and down when in landscape mode.

2021-11-16 14:05 UTC, frosty commented
@diegoreymendez Thanks for the review! I've just merged in the latest from `develop`, which restricts the rotation of this screen so it's only shown in portrait on iPhone. I've also tested on iPad and I'm not seeing the issue there. Is it okay if I go ahead and merge?

2021-11-16 14:59 UTC, diegoreymendez approved these changes

2021-11-16 15:00 UTC, merged