Comments: Show loading message when fetching data
wordpress-mobile/WordPress-iOS pull request #17645
Opened 2021-12-08 14:50 UTC by dvdchr

Refs p1638917701278600-slack-C011BKNU1V5

As titled, this updates the `NoResultsViewController` to show a loading message (and image) while the view controller is fetching data. After the fetch completes, it should show the original "No comments yet" message. Here's a quick recording to show the new message in action:

https://user-images.githubusercontent.com/1299411/145228102-517c58a9-c9b0-4d33-a0f5-a419efd29f54.mp4

## To test

It's best to log out of the app (if you're already logged in) to wipe all the comments from Core Data. 

- Go to My Site > Comments.
- Verify that the comment list shows a "Fetching comments..." loading view before showing a list of comments.
- Tap on one of the filters where there are no comments, e.g. Spam or Trash.
- Verify that the "Fetching comments..." loading view is shown briefly, and a no results view is shown shortly after.
- Do a pull-to-refresh action on the current page.
- Verify that the "Fetching comments..." loading view is shown briefly, and a no results view is shown shortly after.

## Regression Notes
1. Potential unintended areas of impact
The message could be displayed in an incorrect state. 

2. What I did to test those areas of impact (or what existing automated tests I relied on)
Manually tested various refresh scenarios.

3. What automated tests I added (or what prevented me from doing so)
N/A.

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

2021-12-08 20:13 UTC, ScoutHarris requested changes

2021-12-08 20:13 UTC, ScoutHarris commented on WordPress/Classes/ViewRelated/Comments/CommentsViewController.m
> -
I _think_ removing this is causing the NRV to be misplaced sometimes. On a fresh install on an iPhone, going to a Comment filter with no Comments the NRV is too low:

<kbd>![misplaced](https://user-images.githubusercontent.com/1816888/145277024-bbb94b14-41a8-4772-a59e-0d4667e10e72.png)</kbd>

Going back to My Site and selecting Comments again, the NRV is now placed correctly:

<kbd>![correct](https://user-images.githubusercontent.com/1816888/145277094-e69142af-0efe-4d65-87cf-3a8f9ce60c05.png)</kbd>

FWIW, for testing I removed the `[self adjustNoResultViewPlacement]` call on line 700. That fixed it on iPhone, but then caused it to be misplaced on iPad.

2021-12-09 11:09 UTC, dvdchr commented
> I think removing this is causing the NRV to be misplaced sometimes.

Thanks! It's strange how it only happens on the app's first run. I've addressed this in https://github.com/wordpress-mobile/WordPress-iOS/pull/17645/commits/e9eddd432c82deb2e6c5f387db5bf084ac7edc7d and I've tested it in iPhone, iPad, and iPhone Max. Tested both the first runs and subsequent runs – and it all looks great on my end.

2021-12-09 18:47 UTC, ScoutHarris approved these changes
LGTM!

:shipit:

2021-12-10 03:42 UTC, merged

2021-12-10 03:42 UTC, dvdchr commented
Thanks @ScoutHarris !