Notifications: Add confirmation action sheet for mark all as read button
wordpress-mobile/WordPress-iOS pull request #17808
Opened 2022-01-24 22:35 UTC by alpavanoglu

Ref #17135

To test:
* Emable Mark All As Read feature flag
* Go to Notifications.
* Tap on checkmark button
* Check if a confirmation sheet is displayed. 
* Cancel action should cancel without any modification.
* Mark All As Read action should mark notifications under that filter as read.

## Regression Notes
1. Potential unintended areas of impact
One thing I noticed is that if one marks all notifications as read the NoticeView is displayed. As it takes some time to disappear, if we mark a notification as unread OR go to another filter and tap on the Mark button again, the sheet stays behind the NoticeView causing an ugly look. But I assume this is a known behavior as it appears on the top of the hierarchy.

2. What I did to test those areas of impact (or what existing automated tests I relied on)
N/A

3. What automated tests I added (or what prevented me from doing so)
The change is in the UI layer. Testing the presentation would require refactoring outside of the scope this PR.

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.

2022-01-24 23:52 UTC, ScoutHarris commented
🤔 I think in this case maybe an alert is better? It's more concise and less verbose. Also, saying `mark all notifications as read` is a bit misleading as it's only doing so for the selected filter. What do you think about customizing the message for the selected filter? We could add another `title` property to Notification's `FilterTabBar` that provides the type to display in the message. I think it would be more accurate and would avoid confusion.

| <img width="450" alt="Screen Shot 2022-01-24 at 4 39 05 PM" src="https://user-images.githubusercontent.com/1816888/150883454-6fdcfaf1-5dff-44b9-ad06-a6260a864b22.png"> | <img width="451" alt="Screen Shot 2022-01-24 at 4 37 41 PM" src="https://user-images.githubusercontent.com/1816888/150883458-48b5ab89-9807-448b-be58-f71ef9aa9ee2.png"> |
|--------|-------|

2022-01-25 00:10 UTC, alpavanoglu commented
Personally I find the action sheet to have smoother experience on happy paths and the alerts more suitable for unexpected things, errors and such. As this is engraved in the happy path, I find it less intrusive. Maybe apart of me still hears the windows error sound :]
Nevertheless I can of course make it an alert if you prefer. And the title point is certainly valid. Would that type be different than the titles we are using there?

2022-01-25 00:28 UTC, ScoutHarris commented
> Personally I find the action sheet to have smoother experience on happy paths 

That's fine, we can use an action sheet. I just think we can reduce the repetitive wording. If we can make it look and read better, that's perfectly fine. 

> Would that type be different than the Filter Tab Titles we are using there?

I think so. Saying "Mark all Comments notifications as read?" or "Mark all Likes notifications as read?" to me doesn't read correctly. Plus, we try not to capitalize words in sentences unless they are proper nouns.

2022-01-25 00:31 UTC, alpavanoglu commented
Alright that makes sense. I will do that 👍🏽

2022-01-25 21:51 UTC, ScoutHarris requested changes
Hey @alpavanoglu . I left a couple small suggestions. In addition, the `All` message has the word `all` duplicated:

<img width="300" alt="Screen Shot 2022-01-25 at 2 45 07 PM" src="https://user-images.githubusercontent.com/1816888/151065731-95910a96-0f56-42a2-8c24-35dc2bbdbcae.png">

2022-01-25 21:51 UTC, ScoutHarris commented on WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationsViewController.swift
> +            comment: "Confirmation title for marking all notifications as read."
Let's add an explanation to the `comment` indicating what the `%1$@` is for. Something like `%1$@ is a placeholder for the notification type.`

2022-01-25 21:51 UTC, ScoutHarris commented on WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationsViewController.swift
> +            "Ok",
A quick search shows we typically use `OK` instead of `Ok`.

2022-01-25 21:51 UTC, ScoutHarris commented on WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationsViewController.swift
> +            case .like:     return NSLocalizedString("like", comment: "Filter likes confirmation tab name")
Let's improve these `comment`s a bit. I don't think these would be clear to a translator what they're for. How about something like `Displayed in the confirmation alert when marking <type> notifications as read.`?

2022-01-25 22:56 UTC, ScoutHarris approved these changes
NICE! 🎉 

:shipit:

2022-01-25 22:56 UTC, merged