Remove CircleCI
wordpress-mobile/WordPress-iOS pull request #17891
Opened 2022-02-04 02:14 UTC by jkmassel

Removes CircleCI – replacing its last use (release builds) with API calls to Buildkite.

2022-02-04 03:01 UTC, jkmassel commented
<!-- REUSE_ID: jetpack-installable-build-link -->You can test the <strong>Jetpack</strong> changes on this Pull Request by downloading it from AppCenter <a href='https://install.appcenter.ms/orgs/automattic/apps/jetpack-installable-builds/'>here</a> with build number: <code>pr17891-b9ad258</code>. IPA is available <a href='https://appcenter-filemanagement-distrib2ede6f06e.azureedge.net/40e1ecc5-32ac-43bf-98fb-bff1a5b57400/Jetpack%20Alpha.ipa?sv=2019-02-02&sr=c&sig=Nd0Z8XVeWbO32HPk1PluKLMcXdJ6AIa4aICnE4DLywE%3D&se=2022-02-05T03%3A00%3A58Z&sp=r'>here</a>. If you need access to this, you can ask a maintainer to add you.

2022-02-04 03:03 UTC, jkmassel commented
<!-- REUSE_ID: installable-build-link -->You can test the <strong>WordPress</strong> changes on this Pull Request by downloading it from AppCenter <a href='https://install.appcenter.ms/orgs/automattic/apps/WPiOS-One-Offs/'>here</a> with build number: <code>pr17891-b9ad258</code>. IPA is available <a href='https://appcenter-filemanagement-distrib5ede6f06e.azureedge.net/95c3c711-1373-4c42-9ecb-e88cb4d033d6/WordPress%20Alpha.ipa?sv=2019-02-02&sr=c&sig=DhyMR5pMYbejz8PDgxPQXrTQIFwzvVngi1zMW8kDlTs%3D&se=2022-02-05T03%3A02%3A46Z&sp=r'>here</a>. If you need access to this, you can ask a maintainer to add you.

2022-02-04 03:26 UTC, jkmassel commented
@mokagio – this should be the last piece of the puzzle – once this lands you should have all the Buildkite tooling as part of the next release!

2022-02-04 09:57 UTC, mokagio requested changes
Apologies @jkmassel, I just noticed I missed something when reviewing #17862. 

I could be wrong, but it looks to me like there is no way currently to tell the `release-builds.yml` pipeline whether it should build a beta or a stable build. In practice, I'm pretty sure the only difference is in the GitHub release always being a stable one (i.e. not having the "pre-release" checkbox selected) but I think it's something we ought to address.

I know you're AFK today and this work affect me directly, so I'm going to:

- Request changes to avoid this being merged accidentally
- Open a PR against this branch to address this

2022-02-04 09:57 UTC, mokagio commented on README.md
> +[![Build status](https://badge.buildkite.com/2f3fbb17bfbb5bba508efd80f1ea8d640db5ca2465a516a457.svg)](https://buildkite.com/automattic/wordpress-ios)
We could also remove this wholesale, given GitHub reports the build status for each commit these days, something that didn't happen at the time the badges became trendy.

2022-02-04 12:00 UTC, mokagio commented
> Open a PR against this branch to address this

https://github.com/wordpress-mobile/WordPress-iOS/pull/17893

2022-02-09 21:41 UTC, mokagio approved these changes
Now that both the fix to differentiate between beta and stable and the release toolkit update have been implemented, we can ship this!

Looking forward test this in action as soon as there'll be a new 19.2 beta to ship 🚀

2022-02-09 21:41 UTC, merged

2022-02-09 21:43 UTC, mokagio commented
Ouch!

Auto-merge kicked in because there are no GitHub checks requirements on the release branch 🤔 

<img width="962" alt="image" src="https://user-images.githubusercontent.com/1218433/153295139-2ee2ea7c-4ae6-46f0-9eb4-581641004bc2.png">

2022-02-09 21:50 UTC, mokagio commented
It looks like Octokit exposes a way to set required checks while setting the branch protection: https://github.com/octokit/octokit.rb/blob/35d968fddf43f8cd7618e082e17e958be67964f1/spec/octokit/client/repositories_spec.rb#L225-L228

Maybe we should look into updating the release toolkit to use that? 🤔

2022-02-11 00:12 UTC, jkmassel commented
> Maybe we should look into updating the release toolkit to use that? 🤔

Agreed!!

2022-02-11 11:56 UTC, AliSoftware commented
@mokagio that's why I opened pdnsEh-7d-p2 :D Maybe it would be worth bumping the priority of that one a bit, especially given it probably won't take _that much_ time to implement? (famous last words…)