Blogging Prompts: Initial prompt dashboard card
wordpress-mobile/WordPress-iOS pull request #18251
Opened 2022-03-31 14:07 UTC by dvdchr

Refs #18250

<img width="405" alt="Screen Shot 2022-03-31 at 21 04 41" src="https://user-images.githubusercontent.com/1299411/161074170-cee6e61f-0965-4ca9-9cdf-372627a9f178.png">

This adds the initial prompt card for the new dashboard. Please note these are not implemented yet and will be addressed in future PRs:

- Train of avatars & the number of prompt answers  
- Contextual menu
- Buttons for the "answered" state
- Actual button actions
- Prompt card in Blog Detail

To test:

- Turn on `Blogging Prompts` and `My Site Dashboard` feature flags.
- Kill the app, and open it again (so the new dashboard appears).
- 🔍 Verify that the prompt card appears correctly (except those that are noted above).

## Regression Notes
1. Potential unintended areas of impact
N/A. Feature is under development.

2. What I did to test those areas of impact (or what existing automated tests I relied on)
N/A. Feature is under development.

3. What automated tests I added (or what prevented me from doing so)
N/A. Feature is under development.

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

2022-03-31 17:32 UTC, ScoutHarris commented
Hey @dvdchr .

On an iPhone, when first showing the Dashboard, the card doesn't display correctly and the app becomes unresponsive. I reproduced it on several simulators and 1 device, so I don't think it's a fluke. 

Simulators: iPhone 11 Pro Max, iPhone 12, 12 Pro Max (iOS 15.4)
Device: iPhone 11 Pro Max (iOS 15.4)

This is what I did:

- Enabled both feature flags in Xcode, before running the app.
- Ran the app.
- Switched to the `Home` tab.
- The app is then unresponsive. It doesn't crash, it just doesn't do anything.
- The prompt card looks like this:

![initial_launch](https://user-images.githubusercontent.com/1816888/161115308-4b079aa8-84ed-42fa-bbb3-0e34d5139319.png)


When rerunning the app, everything is fine - the card shows properly and the app is responsive. I couldn't repro it on iPad, it seems to work fine there.

2022-03-31 17:33 UTC, ScoutHarris requested changes
See comment re iPhone initial launch.

2022-04-01 08:48 UTC, dvdchr commented
> the card doesn't display correctly and the app becomes unresponsive.

Well, that is strange indeed.  Thanks for catching that! 🙂 It looks like the views are added correctly, which means the `configure` method is called, but somehow the autolayout is broken. I've tried reproducing the issue in iPhone 8 (15.2) and iPhone 11 Pro Max (15.2), but I couldn't get it to reproduce, even though I've enabled the feature flags from code 🤔 . 

> Switched to the Home tab.

In my case the Home tab appears first 🤔  so I didn't have to switch tabs. Anyways, I've tried these, but with did not see the bug appearing:

- Enabled both feature flags from code.
- Modifying `MySiteViewController` so that the Site Menu appears first.
- Doing a fresh install on the app, and 
- 

Perhaps it's got something to do with iOS 15.4? I'm downloading Xcode 13.3 to test this.

2022-04-01 12:39 UTC, leandroalonso commented
@dvdchr 

> In my case the Home tab appears first 🤔 so I didn't have to switch tabs.

This is because of the AB test. :)

2022-04-01 13:44 UTC, dvdchr commented
> This is because of the AB test. :)

That explains it. Thank you! 🙂

2022-04-01 17:52 UTC, ScoutHarris commented
Just to cross reference, the issue for the app freezing - https://github.com/wordpress-mobile/WordPress-iOS/issues/18256.

2022-04-01 18:47 UTC, ScoutHarris approved these changes

2022-04-03 21:27 UTC, mokagio requested changes, later dismissed
The Jetpack Installable build [failed](https://buildkite.com/automattic/wordpress-ios/builds/6457#b0b1ccbe-d2c6-4c44-a64a-be71f45929e5/2317-9691) with an error that is worth looking into:

```
❌  /usr/local/var/buildkite-agent/builds/builder/automattic/wordpress-ios/WordPress/Classes/ViewRelated/Blog/Blog Dashboard/DashboardCard.swift:52:20: cannot find 'DashboardPromptsCardCell' in scope
 
            return DashboardPromptsCardCell.self
```

From the looks of it the new `DashboardPromptsCardCell` is not part of the Jetpack target. If that's the case, the Jetpack build will fail in the App Store configuration, too, which would block the code freeze.

I might be able to do that myself later, but I'm going to request changes for the time being to avoid this PR getting merged and delay the code freeze. I'll leave this in the 19.6 milestone and we can ship a new beta for it if not fixed before the code freeze starts.

2022-04-04 08:36 UTC, dvdchr commented
@mokagio thanks for the information! Since this is still a WIP, I'll fix this and target this for 19.7. 🙂

2022-04-05 01:12 UTC, mokagio commented
Nice one @dvdchr , thanks!

2022-04-05 01:46 UTC, merged