Stats Revamp: Views Visitors Card and Graph
wordpress-mobile/WordPress-iOS pull request #18509
Opened 2022-05-04 15:21 UTC by sla8c

This PR adds a new Views / Visitors Graph and Card to the Insights screen as part of Stats Revamp

Fixes #18234
Fixes #18235

Design
<img width="207" alt="image" src="https://user-images.githubusercontent.com/88816724/166713203-d8f3a40d-a055-448f-8aa8-8b538cc1b7ca.png">

Implementation
<img width="220" alt="image" src="https://user-images.githubusercontent.com/88816724/166713488-489f0cd5-4cab-40a8-82f6-a642f44120b4.png">

To test:
1. First, build and run, navigate to Stats Insights for a site and ensure that there is no option to add a Views & Visitors card like in s/shot below
<img width="221" alt="image" src="https://user-images.githubusercontent.com/88816724/166713693-f8e3a419-dd1b-44db-8a35-62b5d4384c61.png">

2. Now enable both of the new stats feature flags and build and run again
	
```
	statsNewAppearance
	statsNewInsights
```
	
3. Add New Stats Card = Views & Visitors
	
4. New Views & Visitors Card and Graph should be added to the screen like the Implementation screenshot above

5. Tap on the Graph.  
		a. Tapping on the Graph will select the nearest whole day to where you have tapped
		b. A marker should appear with the information that was also in the design
		c. A dotted vertical line should appear on the day that was displayed
		d. A circle / dot will display on the Y axis for the selected date at the Y intercept
6. Tap on the edges of the Graph
		a. The stem of the marker should change to nicely render the marker away from the edges like in the following screenshot(s)
<img width="210" alt="image" src="https://user-images.githubusercontent.com/88816724/166713746-bc2ec3a6-6e08-4c7b-8a55-4371e7d4c7ab.png">
<img width="207" alt="image" src="https://user-images.githubusercontent.com/88816724/166713789-14c42cda-edb9-4736-b01d-a98a0deb5324.png">

## Regression Notes
1. Potential unintended areas of impact
Stats Insights

2. What I did to test those areas of impact (or what existing automated tests I relied on)
Manually tested + created a UnitTest for Domain object usage in ViewModel

3. What automated tests I added (or what prevented me from doing so)
ViewModel UnitTest

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

2022-05-06 13:22 UTC, frosty reviewed
This is looking fantastic! Looks great, and works really well. I haven't finished going through everything yet but thought I'd post a partial review. I'll post another for the rest later.

2022-05-06 13:22 UTC, frosty commented on WordPress/Classes/ViewRelated/Stats/Charts/StatsLineChartView.swift
> +        if let specifiedAnalyticsGranularity = analyticsGranularity {
We may want to add a property here to specify which chart it is – views vs visitors. Also I suppose there's the possibility we may add other similar charts in the future.

2022-05-06 13:22 UTC, frosty commented on WordPress/Classes/ViewRelated/Stats/Charts/InsightsLineChart.swift
> +            rawChartData.forEach { statsSummaryTimeIntervalDataAsAWeek in
I'd love it if there was a way to reuse some of the duplicated code in here, but I appreciate it's not easy here! I came up with the following, which eliminates some of it but I don't know if it's that much better:

```
    func filterData(path: KeyPath<StatsSummaryData, Int>) -> (thisWeekEntries: [ChartDataEntry], prevWeekEntries: [ChartDataEntry]){
        var thisWeekEntries = [ChartDataEntry]()
        var prevWeekEntries = [ChartDataEntry]()

        rawChartData.forEach { statsSummaryTimeIntervalDataAsAWeek in
            switch statsSummaryTimeIntervalDataAsAWeek {
            case .thisWeek(let data):
                thisWeekTotal = data.summaryData.compactMap({$0[keyPath: path]}).reduce(0, +)

                for (index, statsSummaryData) in data.summaryData.enumerated() {
                    thisWeekEntries.append(ChartDataEntry(x: Double(index), y: Double(statsSummaryData[keyPath: path])))
                }
            case .prevWeek(let data):
                prevWeekTotal = data.summaryData.compactMap({$0[keyPath: path]}).reduce(0, +)

                for (index, statsSummaryData) in data.summaryData.enumerated() {
                    prevWeekEntries.append(ChartDataEntry(x: Double(index), y: Double(statsSummaryData[keyPath: path])))
                }
            }
        }

        return (thisWeekEntries: thisWeekEntries, prevWeekEntries: prevWeekEntries)
    }


    func transform() -> (lineChartData: [LineChartDataConvertible], lineChartStyling: [LineChartStyling]) {
        var thisWeekEntries = [ChartDataEntry]()
        var prevWeekEntries = [ChartDataEntry]()

        switch filterDimension {
        case .views:
            (thisWeekEntries, prevWeekEntries) = filterData(path: \StatsSummaryData.viewsCount)
        case .visitors:
            (thisWeekEntries, prevWeekEntries) = filterData(path: \StatsSummaryData.visitorsCount)
        }
```

2022-05-06 13:22 UTC, frosty commented on WordPress/Classes/ViewRelated/Stats/Charts/InsightsLineChart.swift
> +        let chartStyling: [LineChartStyling] = [
We could move this into a static constant. The `primaryLineColor`, `secondaryLineColor`, and `primaryHighlightColor` methods used below could be too.

2022-05-06 13:22 UTC, frosty commented on WordPress/Classes/ViewRelated/Stats/Charts/InsightsLineChart.swift
> +        let horizontalAxisFormatter = HorizontalAxisFormatter(initialDateInterval: 1.0, period: .day)
I'm not sure this is used?

2022-05-06 13:22 UTC, frosty commented on WordPress/Classes/ViewRelated/Stats/Charts/InsightsLineChart.swift
> +        var chartData = [LineChartData]()
I wonder if we could extract the rest of this into another method, just as this one is getting quite long?

2022-05-06 13:22 UTC, frosty commented on WordPress/Classes/ViewRelated/Stats/Charts/InsightsLineChart.swift
> +    func secondaryLineColor() -> UIColor {
Could these be `var`s or `let`s?

2022-05-06 13:22 UTC, frosty commented on WordPress/Classes/ViewRelated/Stats/Charts/InsightsLineChart.swift
> +        static var primaryHighlightColor: UIColor {
Could this be a let?

2022-05-06 13:22 UTC, frosty commented on WordPress/Classes/ViewRelated/Stats/Charts/InsightsLineChart.swift
> +    let legendTitle: String?                        = NSLocalizedString("Views", comment: "This appears in the legend of the insights line chart")
This comment could be slightly clearer to give a little more context: "Title for Views count in the legend of the Stats Insights views and visitors line chart". Similar for the visitors one below.

2022-05-06 13:22 UTC, frosty commented on WordPress/Classes/ViewRelated/Stats/Charts/InsightsLineChart.swift
> +    func transform() -> (lineChartData: [LineChartDataConvertible], lineChartStyling: [LineChartStyling]) {
Could we add a few comments into this method to clarify what's happening?

2022-05-06 13:22 UTC, frosty commented on WordPress/Classes/ViewRelated/Stats/Charts/StatsLineChartConfiguration.swift
> +    init(data: LineChartDataConvertible, styling: LineChartStyling, xAxisDates: [Date]) {
I'm not sure these initializers are used?

2022-05-10 14:00 UTC, frosty requested changes
Okay, all looking good functionally to me – I see the chart update fixed the 1st data point issue. I've added a few more code level comments for you, but nothing major!

2022-05-10 14:00 UTC, frosty commented on WordPress/Classes/ViewRelated/Stats/Charts/StatsLineChartView.swift
> +        // TODO having issue with horizontalBezier (smoothing) - issue seems to be with this old version of lib
I think we can remove this comment now we've updated the library.

2022-05-10 14:00 UTC, frosty commented on WordPress/Classes/ViewRelated/Stats/Charts/StatsLineChartView.swift
> +            xAxis.axisLineDashLengths = [Constants.xAxisTickWidth, (contentWidthMinusTicks / CGFloat(xAxisDates.count - 1))]
Is there ever a case that xAxisDates.count could be 1? (so, divide by zero)

2022-05-10 14:00 UTC, frosty commented on WordPress/Classes/ViewRelated/Stats/Insights/SiteStatsInsightsViewModel.swift
> +    private var currentEntryIndex: Int = 0
Could we add a comment to explain what this is for?

2022-05-10 14:00 UTC, frosty commented on WordPress/Classes/ViewRelated/Stats/Insights/SiteStatsInsightsViewModel.swift
> +        case let count where count == 14:
We should probably have a constant for `14`, as it's used in multiple places throughout this method.

2022-05-10 14:00 UTC, frosty commented on WordPress/Classes/ViewRelated/Stats/Insights/ViewsVisitors/ViewsVisitorsLineChartCell.swift
> +        let differenceText = String(format: NSLocalizedString("Your last week's %@ are %@ %@ than the previous week.", comment: "Your last week's stats compared to previous week"), segmentTitle.local
We'll need to do this a slightly different way, as we can't be sure that simply inserting a translation for 'higher' or 'lower' into the string will be grammatically correct in other languages. On Android, we've gone with 4 complete sentences:

> Your views this week are %1$s higher than the previous week.
> Your views this week are %1$s lower than the previous week.
> Your visitors this week are %1$s higher than the previous week.
> Your visitors this week are %1$s lower than the previous week.

2022-05-10 14:00 UTC, frosty commented on WordPress/Classes/ViewRelated/Stats/Insights/ViewsVisitors/ViewsVisitorsLineChartCell.swift
> +        let differenceText = String(format: NSLocalizedString("Your last week's %@ are %@ %@ than the previous week.", comment: "Your last week's stats compared to previous week"), segmentTitle.local
Also I think 'this week' rather than 'last week' is less confusing as we're comparing it to the 'previous week' (which to me I would also call 'last week'.

2022-05-12 10:52 UTC, sla8c commented on WordPress/Classes/ViewRelated/Stats/Charts/StatsLineChartView.swift
> +        if let specifiedAnalyticsGranularity = analyticsGranularity {
Sounds great + done!

2022-05-12 10:52 UTC, sla8c commented on WordPress/Classes/ViewRelated/Stats/Charts/InsightsLineChart.swift
> +            rawChartData.forEach { statsSummaryTimeIntervalDataAsAWeek in
Done!

2022-05-12 10:53 UTC, sla8c commented on WordPress/Classes/ViewRelated/Stats/Charts/InsightsLineChart.swift
> +        let chartStyling: [LineChartStyling] = [
These are carryovers from PeriodChart. For the card what I did first was added a card that would display the PeriodChart and I based InsightsLineChart off PeriodChart.

I tried to keep InsightsLineChart perhaps hybrid + keeping some of PeriodChart's re-usablity but for the sake of ease + naming the class InsightsLineChart I've removed PeriodChart's structure

2022-05-12 10:53 UTC, sla8c commented on WordPress/Classes/ViewRelated/Stats/Charts/InsightsLineChart.swift
> +        let horizontalAxisFormatter = HorizontalAxisFormatter(initialDateInterval: 1.0, period: .day)
Another PeriodChart carryover - removed + thanks!

2022-05-12 10:53 UTC, sla8c commented on WordPress/Classes/ViewRelated/Stats/Charts/InsightsLineChart.swift
> +        var chartData = [LineChartData]()
Done!

2022-05-12 10:54 UTC, sla8c commented on WordPress/Classes/ViewRelated/Stats/Charts/InsightsLineChart.swift
> +    func secondaryLineColor() -> UIColor {
Another PeriodChart carryover - updated + thanks!

2022-05-12 10:54 UTC, sla8c commented on WordPress/Classes/ViewRelated/Stats/Charts/InsightsLineChart.swift
> +        static var primaryHighlightColor: UIColor {
Done!

2022-05-12 10:54 UTC, sla8c commented on WordPress/Classes/ViewRelated/Stats/Charts/InsightsLineChart.swift
> +    let legendTitle: String?                        = NSLocalizedString("Views", comment: "This appears in the legend of the insights line chart")
Np - done!

2022-05-12 10:55 UTC, sla8c commented on WordPress/Classes/ViewRelated/Stats/Charts/InsightsLineChart.swift
> +    func transform() -> (lineChartData: [LineChartDataConvertible], lineChartStyling: [LineChartStyling]) {
Np - done!

2022-05-12 10:55 UTC, sla8c commented on WordPress/Classes/ViewRelated/Stats/Charts/StatsLineChartConfiguration.swift
> +    init(data: LineChartDataConvertible, styling: LineChartStyling, xAxisDates: [Date]) {
Carryover from StatsBarChartConfiguration - removed + thanks!

2022-05-12 10:55 UTC, sla8c commented on WordPress/Classes/ViewRelated/Stats/Charts/StatsLineChartView.swift
> +        // TODO having issue with horizontalBezier (smoothing) - issue seems to be with this old version of lib
Done!

2022-05-12 10:55 UTC, sla8c commented on WordPress/Classes/ViewRelated/Stats/Charts/StatsLineChartView.swift
> +            xAxis.axisLineDashLengths = [Constants.xAxisTickWidth, (contentWidthMinusTicks / CGFloat(xAxisDates.count - 1))]
Thanks for catching this + done!

2022-05-12 10:56 UTC, sla8c commented on WordPress/Classes/ViewRelated/Stats/Insights/SiteStatsInsightsViewModel.swift
> +    private var currentEntryIndex: Int = 0
This was carryover from StatsPeriodViewModel + pulling in the StatsSummaryTimeIntervalData etc.  I've removed as its not needed in Insights

2022-05-12 10:56 UTC, sla8c commented on WordPress/Classes/ViewRelated/Stats/Insights/SiteStatsInsightsViewModel.swift
> +        case let count where count == 14:
Thanks!  Sorry I missed this one

2022-05-12 10:56 UTC, sla8c commented on WordPress/Classes/ViewRelated/Stats/Insights/ViewsVisitors/ViewsVisitorsLineChartCell.swift
> +        let differenceText = String(format: NSLocalizedString("Your last week's %@ are %@ %@ than the previous week.", comment: "Your last week's stats compared to previous week"), segmentTitle.local
Done! :)

2022-05-12 16:00 UTC, frosty reviewed
Changes look great! Just noticed one last small thing: on the designs, the top line of text in the tooltip should be prefixed with + or - to make it clear it's showing the change from the previous week. After that, let's :shipit:

2022-05-13 04:58 UTC, sla8c commented
> Changes look great! Just noticed one last small thing: on the designs, the top line of text in the tooltip should be prefixed with + or - to make it clear it's showing the change from the previous week. After that, let's :shipit:

Done! Thanks

2022-05-13 08:29 UTC, frosty approved these changes
Looks good to me! :shipit:

2022-05-13 13:27 UTC, merged