My Site Dashboard: Fix crash on non-iOS 15 when loading posts cards
wordpress-mobile/WordPress-iOS pull request #18537
Opened 2022-05-09 03:01 UTC by hassaanelgarem

## Description
- This PR fixes a crash happening on iOS 13 and 14 when loading the dashboard.
- I've also cherry-picked 503c0630a5cde0e674d3534a1fad797e6aa269e6 from #18531 in case we end up closing it.

## Testing Instructions

1. Run the app on iOS 13 or iOS 14
2. Make sure to test using a site with no cached data, so that the ghost cells inside posts card would appear
3. Go to the dashboard
4. ✅ Make sure the post list loads correctly and the app does not crash

## Regression Notes
1. Potential unintended areas of impact
N/A

2. What I did to test those areas of impact (or what existing automated tests I relied on)
N/A

5. What automated tests I added (or what prevented me from doing so)
N/A

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

2022-05-09 09:19 UTC, momo-ozawa approved these changes
Works as described!

2022-05-09 14:33 UTC, leandroalonso requested changes
@hassaanelgarem I still experience the crash. Steps to reproduce:

1. Clean install
2. Login
3. Site with drafts and scheduled
4. Go to the dashboard and 💥

```
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Invalid update: invalid number of sections. The number of sections contained in the table view after the update (3) must be equal to the number of sections contained in the table view before the update (3), plus or minus the number of sections inserted or deleted (3 inserted, 0 deleted).'
CoreSimulator 783.5 - Device: iPhone 12 (52D9936B-889A-4D94-9D49-33BFFE7EA857) - Runtime: iOS 14.5 (18E182) - DeviceType: iPhone 12
```

2022-05-09 16:49 UTC, hassaanelgarem commented
@leandroalonso Thanks for catching this! I was only testing on iOS 13 🙈 
It should be fixed in 1bceaa22558c17b5f401d836d32e551a809fa895

2022-05-09 20:15 UTC, leandroalonso approved these changes
Now it worked just fine! 😎

2022-05-10 02:19 UTC, hassaanelgarem commented
@mokagio FYI

2022-05-10 02:19 UTC, merged

2022-05-10 02:22 UTC, hassaanelgarem commented
@AliSoftware FYI 👍

2022-05-10 12:38 UTC, AliSoftware commented
Thanks for the heads up 🙇 . I'll prepare a new beta with those new PRs if not today (we just had some issues with App Center and internal/beta builds I'll have to focus on first), then tomorrow at the latest.

2022-05-12 10:52 UTC, AliSoftware commented
FYI: This fix has now made its way into the `19.8.0.2` beta 🎉