Blogging Prompts: Update prompts header view attribution label to be dynamic
wordpress-mobile/WordPress-iOS pull request #18610
Opened 2022-05-13 18:16 UTC by wargcm

See #18558

## Description

Updates the attribution label for the header view to be dynamic with the text size. Additionally, changes how the popover size is calculated to better fit the content in the FAB.

## Testing

To test:
- Enable `bloggingPrompts` feature flag
- Launch on an iPhone or iPad
- Navigate to the 'My Site' tab
- Tap on the FAB '+'
- Modify the accessibility font size
- Verify:
  - Header view content fits correctly
  - Attribution label properly resizes
- Repeat same steps with an iPhone or iPad depending on what was used originally

## Screenshots

### iPad

#### Default text size (popover width unchanged)
| Before - Portrait | After - Portrait | Before - Landscape | After - Landscape |
|-----------------|----------------|---------------------|-------------------|
| ![Simulator Screen Shot - iPad Pro (11-inch) (3rd generation) - 2022-05-13 at 13 54 22](https://user-images.githubusercontent.com/2454408/168341243-fba730ed-aa31-488a-bdd9-8b53d7f1de9b.png) | ![Simulator Screen Shot - iPad Pro (11-inch) (3rd generation) - 2022-05-13 at 13 56 01](https://user-images.githubusercontent.com/2454408/168341284-a56dbcd8-786f-48f1-90fd-29d7ba3694f6.png) | ![Simulator Screen Shot - iPad Pro (11-inch) (3rd generation) - 2022-05-13 at 13 54 35](https://user-images.githubusercontent.com/2454408/168341304-0e9fe31a-abe6-4f65-9f62-9555668bbba9.png) | ![Simulator Screen Shot - iPad Pro (11-inch) (3rd generation) - 2022-05-13 at 13 56 09](https://user-images.githubusercontent.com/2454408/168341334-b3ea27be-cfdb-40f4-b394-4fad7a1cb6a0.png) |

#### Large text size (new popover width)

| Before - Portrait | After - Portrait | Before - Landscape | After - Landscape |
|-----------------|----------------|---------------------|-------------------|
| ![Simulator Screen Shot - iPad Pro (11-inch) (3rd generation) - 2022-05-13 at 13 54 52](https://user-images.githubusercontent.com/2454408/168341525-81b888f5-e602-4155-a8eb-35a8ff32a899.png) | ![Simulator Screen Shot - iPad Pro (11-inch) (3rd generation) - 2022-05-13 at 13 56 20](https://user-images.githubusercontent.com/2454408/168341561-eac6a66b-0aad-4262-875c-8c9cf59be3a8.png) | ![Simulator Screen Shot - iPad Pro (11-inch) (3rd generation) - 2022-05-13 at 13 55 00](https://user-images.githubusercontent.com/2454408/168341589-b2f7ab9b-05e2-4c7a-bc70-e4fa38ac2588.png) | ![Simulator Screen Shot - iPad Pro (11-inch) (3rd generation) - 2022-05-13 at 13 56 36](https://user-images.githubusercontent.com/2454408/168341628-60663b5e-507d-40b0-ad39-5d72fe689362.png) |

### iPhone

| Before | After |
|--------|------|
| ![Simulator Screen Shot - iPhone 11 - 2022-05-13 at 14 12 57](https://user-images.githubusercontent.com/2454408/168342963-f48aad58-98bb-4010-bd5f-78f2e9a7e0ec.png) | ![Simulator Screen Shot - iPhone 11 - 2022-05-13 at 14 09 44](https://user-images.githubusercontent.com/2454408/168342587-2115635f-c71e-4b3e-a9bf-ff6da7103157.png) |

## Regression Notes
1. Potential unintended areas of impact
N/A

2. What I did to test those areas of impact (or what existing automated tests I relied on)
N/A

3. What automated tests I added (or what prevented me from doing so)
N/A

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

2022-05-13 18:19 UTC, wargcm commented on WordPress/Classes/ViewRelated/System/Action Sheet/ActionSheetViewController.swift
> +        static let maximumWidth: CGFloat = 600
I based this on some documentation from Apple: https://developer.apple.com/documentation/uikit/uiviewcontroller/1619323-contentsizeforviewinpopover

> The recommended width for popovers is 320 points. If needed, you can return a width value as large as 600 points, but doing so is not recommended.

That property is deprecated now so the documentation might not be up to date but I couldn't find any other guidelines.

2022-05-13 20:33 UTC, ScoutHarris requested changes
Hey @wargcm . Spotted a few issues:

- On iPhone, increase text size then rotate. The top of the sheet is cut off.

![compact_height](https://user-images.githubusercontent.com/1816888/168383156-c014aabf-3f17-4cb1-b4e0-be39770e307f.png)

- With large text on iPhone, the `Create New` actions are pushed off screen and are inaccessible.

![iphone](https://user-images.githubusercontent.com/1816888/168384231-91c8f84b-d2d0-4846-83dc-6de3cd94f7bc.png)

- On iPhone, when increasing then decreasing text size, the prompt view doesn't resize correctly.

![prompt](https://user-images.githubusercontent.com/1816888/168384491-8cfb639b-d888-4d60-9026-f2c28fc3863d.png)

- With large text on iPad, the `Create New` label disappears.

<img width="565" alt="ipad" src="https://user-images.githubusercontent.com/1816888/168385403-cbb8cf29-7eb0-4b51-bd76-ab6615a0006f.png">

2022-05-16 19:38 UTC, iamthomasbishop requested changes
@wargcm Thanks for the ping! I see @ScoutHarris already mentioned some of the things I am seeing, so I only have one note. Not sure if this is specific to dynamic type sizes but the margins on the prompt section of the popover don't seem to be the same as the section below ([example](https://cldup.com/UWU9KgBoPf.png)).

2022-05-16 22:40 UTC, wargcm commented
@ScoutHarris @iamthomasbishop 

> On iPhone, increase text size then rotate. The top of the sheet is cut off.

> With large text on iPhone, the Create New actions are pushed off screen and are inaccessible.

> With large text on iPad, the Create New label disappears.

These should be fixed with: https://github.com/wordpress-mobile/WordPress-iOS/pull/18610/commits/2ac58d81905006a6a2d2263d5b3bd338dd1adcab & https://github.com/wordpress-mobile/WordPress-iOS/pull/18610/commits/e41ad0cd118ed48158abcf45bb4c2c649f8a1050

> On iPhone, when increasing then decreasing text size, the prompt view doesn't resize correctly.

For some reason I wasn't able to reproduce this. If you still see this issue after my changes, I can take a look again.

> Not sure if this is specific to dynamic type sizes but the margins on the prompt section of the popover don't seem to be the same as the section below ([example](https://cldup.com/UWU9KgBoPf.png)).

This was something I missed when I created the view. I added some margins in: https://github.com/wordpress-mobile/WordPress-iOS/pull/18610/commits/bba45c2261b2b3ff2050db6c37eccabec928cb22

Thanks for the reviews! I tried to test a bunch of different cases with my changes but if I missed anything, let me know.

2022-05-17 19:03 UTC, ScoutHarris requested changes
Hey @wargcm .

All the issues I previously noted seem to have been resolved. 🎉 However, there is a shiny new one.

There is a scenario where the app becomes unresponsive:
- In compact height, show the new sheet.
- Attempt to pull down on the sheet to dismiss it.
- The app stops responding.
- I was able to reproduce it with regular text and large text, but more often with large text. On a real device and simulator.

2022-05-17 21:15 UTC, wargcm commented
@ScoutHarris That was a fun one to track down 😆 . It was already an existing issue but didn't occur until the header got added to the view.

To reproduce, you had to pull down the notification center in the same location the pan gesture is. This _sometimes_ causes the pan gesture to begin and then cancel right away. https://github.com/wordpress-mobile/WordPress-iOS/pull/18610/commits/24b342604946b8689ec3a30dc42ba6771fdf5997 should take care of the cancelled state.

Nice catch!

2022-05-17 21:36 UTC, ScoutHarris commented
> It was already an existing issue but didn't occur until the header got added to the view.

Aw sorry to ding you for that! And that explains why I couldn't repro it on the old sheet. I tried! 😆

2022-05-17 21:39 UTC, ScoutHarris approved these changes
I can't find anything else to complain about. 😄 

:shipit:

2022-05-18 14:44 UTC, iamthomasbishop approved these changes
> These should be fixed with: https://github.com/wordpress-mobile/WordPress-iOS/commit/2ac58d81905006a6a2d2263d5b3bd338dd1adcab & https://github.com/wordpress-mobile/WordPress-iOS/commit/e41ad0cd118ed48158abcf45bb4c2c649f8a1050

@wargcm sounds good and thank you!

2022-05-18 15:09 UTC, wargcm commented
Thanks @ScoutHarris & @iamthomasbishop!

2022-05-18 15:09 UTC, merged