Stats Revamp: Details Screen Date Picker
wordpress-mobile/WordPress-iOS pull request #18685
Opened 2022-05-20 12:15 UTC by sla8c

This PR adds functionality for the DatePicker on the Details screen as part of Stats Revamp.
 * The Date Picker now works and makes an API call + refreshes screen for the selected date interval period
 * DatePicker does not show when the tap originated from out of scope cards (ie Tags and Categories) that were not included in Stats Revamp v2

Ref #18601 

To test:
1. First, build and run, navigate to Stats Insights for a site and ensure that there is no option to add a Views & Visitors card like in s/shot below
2. Click around insights, period stats and ensure there are no crashes
3. From the insights screen tap View more on This Year.  There should be no changes compared to current app store version of the app
4. Repeat the same process for Tags and Categories, Followers and Posting Activity

Now enable both of the new stats feature flags and build and run again (`statsNewAppearance, statsNewInsights`)

1. Add New Stats Card = Views & Visitors.  New Views & Visitors Card and Graph should be added to the screen
2. Tap "This week" on the upper right of the Views / Visitors card.  Screen will segue / navigate to the Details card like below
3. Tap the DatePicker at top to go back in time + data will update and tap DatePicker to go forward in time
4. Navigate back to main insights screen and tap View More on This Year.  DatePicker should not be visible on the Details Screen
5. Repeat for Tags and Categories, Followers and Posting Activity

## Regression Notes
1. Potential unintended areas of impact
Stats

2. What I did to test those areas of impact (or what existing automated tests I relied on)
I manually tested and added a unit test

3. What automated tests I added (or what prevented me from doing so)
I added a unit test

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

2022-05-23 10:42 UTC, frosty requested changes
Code looks good to me 👍  I got some crashes when navigating into View More from **This Year**, and **Latest Post Summary** cards with the feature flag disabled, and **This Year** with the feature flag enabled:

```
 *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'invalid nib registered for identifier (SiteStatsTableHeaderView) - nib must contain exactly one top level object which must be a UITableViewHeaderFooterView instance'
```

The only other thing I noticed is that we still need some work on loading states as if you tap the arrows multiple times before the view updates it almost appears like it's showing the wrong data and then correct data may pop in. Although this sometimes seems to happen even when data is cached, so I'm not 100% sure if there's an issue there or not. I can provide a video if that's helpful, and this is something that can be addressed in a future PR.

2022-05-23 10:42 UTC, frosty commented on WordPress/Classes/ViewRelated/Stats/Shared Views/Stats Detail/SiteStatsDetailsViewModel.swift
> +            fetchDataFor(statSection: statSection!,
Is there ever a case this might be nil? Should we unwrap it?

2022-05-25 15:54 UTC, frosty approved these changes
Looks good to me, just one suggestion for improvement! I still can't tap into View More on a card at the Views and Visitors 2nd level, but I'm not sure if that's coming later?

2022-05-25 15:54 UTC, frosty commented on WordPress/Classes/ViewRelated/Stats/Shared Views/Post Stats/PostStatsTableViewController.swift
> +        guard let cell = Bundle.main.loadNibNamed("SiteStatsTableHeaderView", owner: nil, options: nil)?.first as? SiteStatsTableHeaderView else {
We might want to move this nib name string to a constant within SiteStatsTableHeaderView, or perhaps even add a method to that class that loads the nib and returns an instance of the view.

2022-05-25 17:13 UTC, sla8c commented on WordPress/Classes/ViewRelated/Stats/Shared Views/Post Stats/PostStatsTableViewController.swift
> +        guard let cell = Bundle.main.loadNibNamed("SiteStatsTableHeaderView", owner: nil, options: nil)?.first as? SiteStatsTableHeaderView else {
Thanks for the spot - defo + will do in next PR 👍

2022-05-25 20:01 UTC, merged