Blogging Prompts: Add syncing reminder UI with remote prompts schedule
wordpress-mobile/WordPress-iOS pull request #18753
Opened 2022-05-26 20:40 UTC by wargcm

See: #18429

## Description

Syncs the reminders UI with the remote settings if it exists. The order of priority for which schedule to display is as follows:
`Local schedule > Remote prompt settings > None`

So if a user already has reminders scheduled but it wasn't synced with the remote backend, their schedule would still be preserved.

## Testing

To test:
- Enable `bloggingPrompts` feature flag
- Open a site and go to My Site > Menu > Site Settings > Blogging Reminders
- Set a schedule and hit 'Notify me'
- Verify the network call to update the schedule is successful
- Delete the app and relaunch
- Pick the same site and navigate back to the reminders screen
- Verify the schedule matches what was saved

## Regression Notes
1. Potential unintended areas of impact
N/A

2. What I did to test those areas of impact (or what existing automated tests I relied on)
N/A

3. What automated tests I added (or what prevented me from doing so)
N/A

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

2022-05-27 14:58 UTC, dvdchr requested changes
👋🏼 ! Thanks for wrangling this @wargcm. I've got some notes:

- We probably should only prepopulate the reminder settings when `promptRemindersEnabled` is true, so we don't disrupt the current Blogging Reminders flow (without prompts). What do you think? 
- Additionally, since Blogging Prompts is still feature-flagged, we should check if the flag is enabled first before pre-populating the reminders.

2022-05-27 14:58 UTC, dvdchr commented on WordPress/Classes/Models/BloggingPromptSettingsReminderDays+CoreDataClass.swift
> +        ].enumerated().flatMap { (index: Int, isReminderActive: Bool) in
Let's make Xcode happy 😄  (`flatMap` is deprecated)

```suggestion
        ].enumerated().compactMap { (index: Int, isReminderActive: Bool) in
```

2022-05-27 14:58 UTC, dvdchr commented on WordPress/Classes/Models/BloggingPromptSettingsReminderDays+CoreDataClass.swift
> +            }
Nitpick: maybe we could move this out of the `flatMap` closure and put it at the top? And return an empty array instead when the guard condition fails.

2022-05-27 22:30 UTC, wargcm commented
@dvdchr thanks for the `flatMap` catch!

> We probably should only prepopulate the reminder settings when promptRemindersEnabled is true, so we don't disrupt the current Blogging Reminders flow (without prompts). What do you think?

The local settings are favored over the remote settings already. So if they had prompts off and had local reminders already, it wouldn't overwrite their schedule. I don't feel strongly one way or the other about wrapping the syncing behind that bool so I went ahead and made the changes.

> Additionally, since Blogging Prompts is still feature-flagged, we should check if the flag is enabled first before pre-populating the reminders.

I was thinking it wouldn't be a huge deal since the default remote settings already matched the default reminder settings locally. But it's a good call in case the backend ever changes, so I made that change.

2022-05-30 04:31 UTC, dvdchr approved these changes
LGTM!

2022-05-30 04:31 UTC, merged