[Jetpack] Add bottom sheet to jetpack powered button on My Site
wordpress-mobile/WordPress-iOS pull request #19121
Opened 2022-07-28 10:49 UTC by alpavanoglu

This PR adds `JetpackPoweredViewController` to be displayed when the user taps on the JP button. It uses the existing bottom sheet functionality. 2 PR's should follow: Adding animation after Lottie is integrated and connecting the button in the sheet.

I did not add additional flags to this as the entry point is behind a flag itself. Let me know if we should still add another flag for it.

To test:
1. Log in to Wordpress.
2. Enable `Jetpack powered banners and badges` if it isn't already enabled.
3. My Site -> Scroll below until Jetpack powered button is visible.
4. Tap on the button. Verify it opens the bottom sheet.
5. It should not rotate on landscape mode when the sheet is open (I follow the same logic with Blogging Prompts here).

There will be a big gap on top for the animation. Lottie integration will follow with a later PR.

## Regression Notes
1. Potential unintended areas of impact
N/A

3. What I did to test those areas of impact (or what existing automated tests I relied on)
N/A

7. What automated tests I added (or what prevented me from doing so)
Right now it is purely UI. Once we connect the button to deeplink in the bottom sheet, we can add a small VM for that interaction and unit test that.

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

2022-07-28 19:25 UTC, Gio2018 requested changes
Hey @alpavanoglu , I haven't done a full code review yet, but I found a few issues:

1. With larger fonts, the button is cut off (or not even visible depending on the size)2. 
<p align=center>
<img height=400 src=https://user-images.githubusercontent.com/34376330/181618841-d55d7a31-8ceb-4e9e-80d5-c052b2f70b10.png>
</p>
2. In landscape, the sheet is also cut off

<p align=center>
<img height=300 src=https://user-images.githubusercontent.com/34376330/181619058-579200a4-c820-4a1f-b67b-b6e072d47c6c.png>
</p>

I feel that there are too many explicit constraints that are causing these issues.
How about we use an approach similar to what we did with `BloggingRemindersFlowIntroViewController`? That one is a bottom sheet as well, and can resize and hide elements depending on the available space. It uses a `UIStackView` as we briefly discussed on Slack, and if we need different spacing, we can use [setCustomSpacing(_:after:)](https://developer.apple.com/documentation/uikit/uistackview/2866023-setcustomspacing) to achieve that.
Also, I'd leave elements using their intrinsic content size as much as possible instead of fixing them (e.g. label sizes) for the same reason.
lastly, I'd try to standardize distances as much as possible, when they don't significantly change the designs (e.g. if we have spacings that are 45 and 50, I think it's totally fine to set them both to the same value, would you agree @shaunandrews ?)

2022-07-28 22:56 UTC, Gio2018 commented
Hey @alpavanoglu , to better illustrate what I meant by using an approach similar to `BloggingRemindersFlowIntroViewController`, I created this draft [PR](https://github.com/wordpress-mobile/WordPress-iOS/pull/19123), let me know what you think.

2022-07-29 11:17 UTC, alpavanoglu commented
Hey @Gio2018 , thanks for testing the PR. About the constraints, I haven't fixed label sizes.  They are all constrained to top and bottom which should allow them to grow or shrink. The only fixed size is button height which I think is a must as we would want CTA's to have fixed height I think.
For margins, I think it is important that we do have parity between figma & app. Otherwise each author for android and iOS could deviate whenever they feel like. Rather than fixing them to a value when we see fit, I'd argue that we must do so in designs instead. It would also be nice if we followed a rule like 8x to have consistency so that we don't end up with buttons with heights 45, 47, 50 etc.

I would love to fix the issues you've pointed but I think the draft you've created does the same thing with this PR which would leave on of them obsolete. So I guess I should just close this one and review yours? Please let me know what you prefer.

2022-07-29 14:22 UTC, Gio2018 commented
Thanks @alpavanoglu !
>  I think it is important that we do have parity between figma & app.
> Rather than fixing them to a value when we see fit, I'd argue that we must do so in designs instead.

Sorry if it wasn't clear, but this is exactly what I meant, and why I pinged @shaunandrews 

One more bit about the standard sizing, we don't have a fully standardized system in the app yet (and we probably should), but some element are somewhat standardized: for example a large button like the "Get the new Jetpack app" in here  is typically of height 44 (not always, sometimes 48..), Here we have 50. Would you think we should standardize these sizes too @shaunandrews ?

> Please let me know what you prefer.

The approach with the stack view seems to solve the layout issues, what do you think?

2022-07-29 14:41 UTC, alpavanoglu commented
Sure, then I'll close this PR and review & test the one you've opened. Does that make sense?

2022-07-29 15:47 UTC, Gio2018 commented
> Sure, then I'll close this PR and review & test the one you've opened. Does that make sense?

Sounds good to me. I'll convert it from draft asap and add you as a reviewer. Thank you!

2022-07-29 15:55 UTC, closed without merging

2022-08-02 17:10 UTC, shaunandrews commented
> One more bit about the standard sizing, we don't have a fully standardized system in the app yet (and we probably should), but some element are somewhat standardized: for example a large button like the "Get the new Jetpack app" in here is typically of height 44 (not always, sometimes 48..), Here we have 50. Would you think we should standardize these sizes too @shaunandrews ?

Much of this confusion likely comes from my inexperience with the existing patterns and standards. Please, whenever you see something that doesn't feel right (50pt, when everywhere else uses 48pt) use your best judgement and/or ping me directly.