Attempt to use docker to run danger
wordpress-mobile/WordPress-iOS pull request #19459
Opened 2022-10-13 09:03 UTC by crazytonyli

I noticed the TODO in the pipeline.yml and decided to implement it—also a good buildkite learning opportunity for me.

I had to swap the `install_gems` command with `bundle install` since I didn't find a way to let the docker container fetch the `common_plugins`, see [this job output](https://buildkite.com/automattic/wordpress-ios/builds/10356#0183d074-8b8e-4611-90b9-60806484aab3/286-287).

## Regression Notes
1. Potential unintended areas of impact
N/A

2. What I did to test those areas of impact (or what existing automated tests I relied on)
N/A

3. What automated tests I added (or what prevented me from doing so)
N/A

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

2022-10-13 09:21 UTC, crazytonyli commented on .buildkite/pipeline.yml
> +              image: "ruby:2.7"
Maybe we should use the image in Automattic's registry?

2022-10-14 03:43 UTC, jkmassel requested changes
Thanks for taking a look at this!

This is an interesting one – we certainly _could_ do this using Docker, but there's actually an even faster approach we could do. If we use the `android` queue, those workers all have a ruby environment that should be able to run this just fine.

Longer-term, it'd be great to have a `ruby` queue that's persistent to allow for really fast danger runs – just need to work through the security implications before we can implement that.

2022-10-14 05:04 UTC, crazytonyli commented
@jkmassel switched to the android queue in https://github.com/wordpress-mobile/WordPress-iOS/pull/19459/commits/cb49ffe7da36774562d5f5f4fe7273b12db29efb

2022-10-14 19:21 UTC, jkmassel approved these changes

2022-10-17 04:26 UTC, mokagio approved these changes
This is brilliant! Thanks @crazytonyli @jkmassel 

I might give it a go in WordPressKit as well (https://github.com/wordpress-mobile/WordPressKit-iOS/pull/534). Keen to see how it will work for SwiftLint. The tool _can_ run on Linux, fingers crossed.

2022-10-17 22:05 UTC, merged

2022-10-18 07:26 UTC, mokagio commented
> I might give it a go in WordPressKit as well (https://github.com/wordpress-mobile/WordPressKit-iOS/pull/534). Keen to see how it will work for SwiftLint. The tool can run on Linux, fingers crossed.

Unfortunately, even though SwiftLint should run on Linux, there seems to be issues with it at the moment, resulting in the binary not being able to run on our `queue: android` agents. Too bad.