Enable support for the VideoPress block
wordpress-mobile/WordPress-iOS pull request #20100
Opened 2023-02-08 11:29 UTC by SiobhyB

Fixes #

To test:

## Regression Notes
1. Potential unintended areas of impact

2. What I did to test those areas of impact (or what existing automated tests I relied on)

3. What automated tests I added (or what prevented me from doing so)

PR submission checklist:

- [ ] I have completed the Regression Notes.
- [ ] I have considered adding unit tests for my changes.
- [ ] I have considered adding accessibility improvements for my changes.
- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

2023-02-08 15:58 UTC, SiobhyB commented on WordPress/Classes/Models/Blog.m
> +    return self.isHostedAtWPcom;
Enabled only on simple WordPress.com sites for now and added [a task to the project board](https://github.com/orgs/wordpress-mobile/projects/166/views/1?layout=board) for this to eventually be changed to match the web.

2023-02-09 12:30 UTC, fluiddot requested changes
I tested the installable build and noticed that I can add the VideoPress block to a post/page. However, if this block is only meant to be available in development mode (i.e. using `__DEV__` flag), it should not be available in the installable builds.

2023-02-09 12:30 UTC, fluiddot commented on Podfile
> +  gutenberg commit: '0b4b05d499197825893260921c662ed3d45a6f33'
We'd need to update this reference to the latest commit: `364d743d55c79c0eb462a1df79520173bcb8aab9`.

2023-02-09 17:32 UTC, SiobhyB commented
> I tested the installable build and noticed that I can add the VideoPress block to a post/page. However, if this block is only meant to be available in development mode (i.e. using __DEV__ flag), it should not be available in the installable builds.

Thanks for spotting this! I'll look into what's causing this. 🧐

2023-02-10 16:44 UTC, SiobhyB commented
@fluiddot, I've added a fix for this with [this commit](https://github.com/wordpress-mobile/gutenberg-mobile/pull/5459/commits/aa57180bc66c426baa44f43e6e1256edfb728357), thanks again for spotting this! No rush to re-review, I don't plan to begin the merge domino until next week 🙇‍♀️

2023-02-13 11:27 UTC, fluiddot requested changes
> I tested the installable build and noticed that I can add the VideoPress block to a post/page. However, if this block is only meant to be available in development mode (i.e. using __DEV__ flag), it should not be available in the installable builds.

As I mentioned in https://github.com/wordpress-mobile/gutenberg-mobile/pull/5459#pullrequestreview-1295417190, the VideoPress block is no longer available for insertion, however, it's still being rendered as a regular block instead of an unsupported block.

2023-02-14 09:26 UTC, SiobhyB commented
Noting that I'm working to fix the failing builds.

2023-02-14 10:44 UTC, SiobhyB commented
@fluiddot, the newest installable builds have finished generating now, whenever you have availability for taking another look. Thanks in advance! :)

2023-02-14 11:30 UTC, fluiddot approved these changes
LGTM 🎊 !

I checked that the VideoPress block is displayed as unsupported and that can be edited via UBE (Unsupported Block Editor) on Atomic sites.

**NOTE:** On Simple sites when using UBE, it shows a warning due to the block not being available on the site. This is expected as the block on the web hasn't been released yet to users.

_Tested build `pr20100-17ddbb8` on an iPhone 11 (iOS 15.4)._

2023-02-15 11:30 UTC, merged