Remove large titles from the Reader and Notification tab
wordpress-mobile/WordPress-iOS pull request #20272
Opened 2023-03-07 09:08 UTC by salimbraksa

Fixes #20271

## Test Instructions

## Regression Notes
1. Potential unintended areas of impact

2. What I did to test those areas of impact (or what existing automated tests I relied on)

3. What automated tests I added (or what prevented me from doing so)

## PR submission checklist:
- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

2023-03-07 11:53 UTC, osullivanchris requested changes
Looks good so far @salimbraksa ! 

A couple of minor issues, which are pre-existing rather than introduced here. So treat them separately if you want. 

1. The background colour on dark mode for the navigation bar is different on Reader and Notifications. Notifications is the same as Home. So I think it is reader that is incorrect. See image below. Also the color is different between the navigation bar and the top tabs, but that's less of an issue to me. If possible can you tell me what colours or system materials / blurs are being used for these headers?
![IMG_0378](https://user-images.githubusercontent.com/50576199/223414477-9d817fdf-5851-4601-ab91-5e30349793d2.jpg)
![IMG_0377](https://user-images.githubusercontent.com/50576199/223414483-c68588bc-3175-4509-9af2-7b3d26fd37b7.jpg)
![IMG_0376](https://user-images.githubusercontent.com/50576199/223414487-b0643977-18fc-481a-872d-5482fa01fcf5.jpg)

2. On the Reader tab, it would be nice if the top tabs and filter bar hid on scroll. The top tabs on Notifications scroll away correctly. I believe there was some issue with hiding on scroll with the stack of Navigation on Reader. I am not sure what was the cause, but I was hoping that without the large title, the issue might be resolved? If too complex, can be parked for later.

Thanks!

2023-03-07 15:01 UTC, salimbraksa commented
@osullivanchris Thanks for your feedback. To answer your questions:

>The background color on dark mode for the navigation bar is different on Reader and Notifications. Notifications is the same as Home. So I think it is reader that is incorrect. See image below. Also the color is different between the navigation bar and the top tabs, but that's less of an issue to me.

The reason why the navigation bar background in **Reader** is different from the one in **Notifications** / **Home** is because:
- The navigation bar is actually **transparent** in **Reader**. So the color you see is the background color of the whole screen.
- The navigation bar in **Notifications** is opaque and its color is set by the system depending on whether is light or dark mode. ( color named `secondarySystemGroupedBackgroundColor` ).

I'm assuming  somewhere in the code, the navigation bar in Reader is to be transparent. So removing that code should fix the issue.

| Reader | Notifications |
| ------- | ------------- |
| ![](https://user-images.githubusercontent.com/9609223/223455026-e0bb7f0a-ae51-473d-b8ae-4a42b85e5f7a.png) | ![](https://user-images.githubusercontent.com/9609223/223454451-8063b960-9db2-442c-a8fe-91c4bd115124.png) |

>If possible can you tell me what colours or system materials / blurs are being used for these headers?

The colors used in the top tabs in both **Reader** and **Notifications** are:
- Light: White
- Dark: Muriel Gray Shade 100 ( HEX: #101517 )

>On the Reader tab, it would be nice if the top tabs and filter bar hid on scroll. The top tabs on Notifications scroll away correctly. 

I'll look into this but is it okey if I handle these issues separately from this PR?

2023-03-07 15:31 UTC, osullivanchris commented
Thanks for all the helpful explanations. 

That muriel colour is from a really old system that we had 😄  

- I wonder could the top tabs also use secondarySystemGroupedBackgroundColor like the navigation bars?  
- It would also be good to remove whatever transparency is being used on reader so it appears the same as Notifications and My Site

Totally fine to merge this one and address those changes in another PR.

2023-03-09 10:23 UTC, osullivanchris approved these changes

2023-03-09 11:09 UTC, merged