My Site: Hide the Stats row if it is unsupported
wordpress-mobile/WordPress-iOS pull request #20623
Opened 2023-04-28 15:09 UTC by hassaanelgarem

Fixes #20594

## Description
Contributors do not have the permissions to view stats, yet we show the stats button in the My Site Menu. This PR removes the stats button when unsupported.

## Testing Instructions

1. Run the Jetpack app
2. Log in using an account that's added as a contributor to Site A
3. Switch to site A
4. Navigate to the Menu
5. Make sure that the Stats button is not displayed ✅ 
6. Make sure that the whole Traffic section is not displayed ✅ 

## Regression Notes
1. Potential unintended areas of impact
My Site menu for other user roles

2. What I did to test those areas of impact (or what existing automated tests I relied on)
Tested manually

3. What automated tests I added (or what prevented me from doing so)
N/A

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

2023-05-04 16:59 UTC, salimbraksa commented
Hey @hassaanelgarem, I'm not sure if I was able to run the test instructions properly, but I added a **contributor account** to another site ( the owner of this site is another account ), and yet I was able to see the "Stats" row.

<img width="500" alt="CleanShot 2023-05-04 at 17 59 06@2x" src="https://user-images.githubusercontent.com/9609223/236273933-7a287d16-ad0c-4414-813e-9c1431e4803e.png">

2023-05-05 09:26 UTC, momo-ozawa requested changes
@hassaanelgarem @salimbraksa I was able to verify that the traffic section / stats button doesn't show up on the menu when I'm a contributor, but the stats button shows up in the quick actions section in the dashboard.

| Home | Menu |
|--------|--------|
| <img src="https://user-images.githubusercontent.com/6711616/236422163-38c910fd-24a2-4fd4-bd1e-03ae8e026050.png" width=200> | <img src="https://user-images.githubusercontent.com/6711616/236422475-71ac93ce-caf3-45b1-9d82-cb751404a957.png" width=200> |

2023-05-09 14:25 UTC, momo-ozawa approved these changes
I completely missed that you have https://github.com/wordpress-mobile/WordPress-iOS/pull/20624 open for the quick action buttons! Disregard my earlier comment 🙈

2023-05-10 02:52 UTC, hassaanelgarem commented
@salimbraksa Can you share with me what happens when you tap on the Stats button? Do you get a functional Stats view or is it broken like this one?

<img src="https://github.com/wordpress-mobile/WordPress-iOS/assets/25306722/b33c878c-b904-45dd-8318-30980224dab8" width=300>

2023-05-11 13:01 UTC, salimbraksa commented
I can see the stats @hassaanelgarem even though the user is a collaborator in that site.

<img width=400 src="https://github.com/wordpress-mobile/WordPress-iOS/assets/9609223/8756fbf8-8ebc-4805-b93e-ade843e1b041" />

2023-05-11 13:16 UTC, momo-ozawa commented
@salimbraksa On top of a being a contributor, are you by chance also a super admin for that site? If you are, then your super admin priviliges override your contributor role. 

<img src="https://github.com/wordpress-mobile/WordPress-iOS/assets/6711616/0d4f997c-c41f-46e4-ac0e-af6087327b63" width=200>

2023-05-11 14:00 UTC, salimbraksa commented
@momo-ozawa The user is not a Super Admin, I don't think this issue is related to this PR. Would it be possible to invite my user @salimbraksademo ( salim.braksa+demo@gmail.com ) to one of your test sites as a collaborator? 

<img width=400 src="https://github.com/wordpress-mobile/WordPress-iOS/assets/9609223/895e7005-0fab-4cd1-ab8c-65f1944551f5" />"

2023-05-11 14:03 UTC, salimbraksa commented
@momo-ozawa The user is not a Super Admin. Is it possible to invite my user salim.braksa+demo@gmail.com to one of your test sites as a contributor? 

<img width=400 src="https://github.com/wordpress-mobile/WordPress-iOS/assets/9609223/db1df9f1-a019-4996-a94b-d206c6256521" />

2023-05-11 15:55 UTC, salimbraksa commented
@hassaanelgarem Feel free to merge this PR, as the issue I reported seems unrelated to this PR. 🙏

2023-05-11 17:29 UTC, salimbraksa approved these changes

2023-05-12 01:57 UTC, hassaanelgarem commented
@salimbraksa I sent you an invite to a test site we use 👍

2023-05-12 01:57 UTC, merged

2023-05-12 01:59 UTC, salimbraksa commented
> @salimbraksa I sent you an invite to a test site we use 👍 

@hassaanelgarem I've accepted the invite. I tested the PR using your site and it works as expected. LGTM! 🚀