Add support for video attachments in "Send Feedback" form
wordpress-mobile/WordPress-iOS pull request #23421
Opened 2024-07-15 17:52 UTC by kean

- Add support for uploading video in the "Send Feedback" form
- Increase the upload limit to 32 MB
- Add "Preview" button to attachments – I added it for testing the upload quality, but I think it's worth keeping

## To test:

- Verify that you can upload video and that the quality is acceptable – looking for a good trade-off between size and quality

## Regression Notes
1. Potential unintended areas of impact: Send Feedback
2. What I did to test those areas of impact (or what existing automated tests I relied on)

3. What automated tests I added (or what prevented me from doing so)

PR submission checklist:

- [ ] I have completed the Regression Notes.
- [ ] I have considered adding unit tests for my changes.
- [ ] I have considered adding accessibility improvements for my changes.
- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

Testing checklist:
- [ ] WordPress.com sites and self-hosted Jetpack sites.
- [ ] Portrait and landscape orientations.
- [ ] Light and dark modes.
- [ ] Fonts: Larger, smaller and bold text.
- [ ] High contrast.
- [ ] VoiceOver.
- [ ] Languages with large words or with letters/accents not frequently used in English.
- [ ] Right-to-left languages. (Even if translation isn’t complete, formatting should still respect the right-to-left layout)
- [ ] iPhone and iPad. 
- [ ] Multi-tasking: Split view and Slide over. (iPad)

2024-07-15 17:53 UTC, dangermattic commented
<!--
  1 Error: PR requires at least one label...
  1 Warning: PR is not assigned to a milest...
  0 Messages
  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">PR requires at least one label.</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">PR is not assigned to a milestone.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2024-07-16 18:36 UTC, jkmassel requested changes
Adding a video worked well.

However, the animation to enter preview mode flashes through black and looks sort of broken. If we can't make it work smoothly I'd suggest we remove it for now (even though I agree it's pretty helpful!)

2024-07-16 21:41 UTC, kean commented
> However, the animation to enter preview mode flashes through black and looks sort of broken.

It works pretty well on the physical devices but not in a simulator. But I was able to break it on the physical device as well. I don't think this features is _needed_, so let's just remove it.

Weird, I've been having some issue uploading attachments using when logged in using my A8C account, and I think it's an existing issue and wasn't part of this PR:

```
Login error: Error Domain=com.zendesk.sdk.core Code=1000 "forbidden" UserInfo={NSLocalizedDescription=forbidden, HTTP Status code=403, description=Only end users are allowed to authenticate with the Mobile SDK, error=OnlyEndUsersAllowed}
```

I know there is some special-case code for A8C access.

2024-07-17 19:56 UTC, jkmassel commented
> I know there is some special-case code for A8C accs.

Yeah this has always been annoying.

Do we have an open issue for it? I'm thinking we could rewrite @automattic.com addresses to something else to avoid it?

2024-07-17 20:06 UTC, jkmassel approved these changes
Tested again and still looks good.

2024-07-17 20:56 UTC, merged