Site List – Features
wordpress-mobile/WordPress-iOS pull request #23432
Opened 2024-07-19 23:31 UTC by kean

## Changes

- Add context menu with a preview
- Add swipe actions
- Add iPad support
- Show placeholder with a first letter of the site name when the icon isn't set
- Add pull-to-refresh
- Add post sync call on view appear
- Add integration with the stats widget (should ideally be extracted to a server in the future)
- Fix navigation bar style in dark mode (required UIKit changes)

## Next Steps

- Integrate the new screen in the domain picker (PR#3)
- Remove the old code (PR#4)

I'm not sure it's worth adding any more features from wp.com. 

Adding filters is not a very compelling features considering most users have only have a handful of sites. If we were to add filters, I'm not sure the ones on wp.com are the right ones. Why would you want to filter by the visibility? It would probably make some sense to separate self-hosted and wp.com sites. Maybe it should be done by default using list sections, wdyt, @jkmassel ?

It's also hard to imagine a scenario where anyone would use these navigation actions on mobile. It's also just going to duplicate the home page.

<img width="298" alt="Screenshot 2024-07-19 at 7 30 47 PM" src="https://github.com/user-attachments/assets/4c748b3e-137e-4505-b640-ae67f6bf576c">

## Screenshots

<img width="320" alt="Screenshot 2024-07-19 at 7 12 27 PM" src="https://github.com/user-attachments/assets/e94438cc-2ef8-473b-84b4-36d9b4cb6638">
<img width="320" alt="Screenshot 2024-07-19 at 7 12 51 PM" src="https://github.com/user-attachments/assets/97f58931-8aaa-4a5a-914d-4c8b6625eb1d">
<img width="460" alt="Screenshot 2024-07-19 at 7 23 54 PM" src="https://github.com/user-attachments/assets/b9f79180-b1fa-4049-8759-af710969de0d">
<img width="320" alt="Screenshot 2024-07-19 at 7 26 41 PM" src="https://github.com/user-attachments/assets/c9b52c61-3de6-4497-8c49-ecf36c204091">
<img width="320" alt="Screenshot 2024-07-19 at 7 26 46 PM" src="https://github.com/user-attachments/assets/bc3989bf-7db6-417c-8bf3-5035d7d769bf">

## Regression Notes
1. Potential unintended areas of impact

2. What I did to test those areas of impact (or what existing automated tests I relied on)

3. What automated tests I added (or what prevented me from doing so)

PR submission checklist:

- [ ] I have completed the Regression Notes.
- [ ] I have considered adding unit tests for my changes.
- [ ] I have considered adding accessibility improvements for my changes.
- [ ] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

Testing checklist:
- [ ] WordPress.com sites and self-hosted Jetpack sites.
- [ ] Portrait and landscape orientations.
- [ ] Light and dark modes.
- [ ] Fonts: Larger, smaller and bold text.
- [ ] High contrast.
- [ ] VoiceOver.
- [ ] Languages with large words or with letters/accents not frequently used in English.
- [ ] Right-to-left languages. (Even if translation isn’t complete, formatting should still respect the right-to-left layout)
- [ ] iPhone and iPad. 
- [ ] Multi-tasking: Split view and Slide over. (iPad)

2024-07-19 23:32 UTC, dangermattic commented
<!--
  1 Error: PR requires at least one label...
  0 Warnings
  0 Messages
  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">PR requires at least one label.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2024-07-22 23:29 UTC, jkmassel requested changes
I'm not sure that the swipe actions are adding all that much?

The long-press-to-preview thing is cool, but we should probably show some feedback about what's going on, then swap in the `WebView` once the page starts actually rendering? I also wonder if we could get away with just the context menu at first, then if someone wants to view the site they can?

The new derived icons look great, though they make the Blog Root Screen look less nice 😅

2024-07-22 23:47 UTC, kean commented
> I'm not sure that the swipe actions are adding all that much?

It's just table stakes to have these for common actions. They don't hurt.

> The long-press-to-preview thing is cool, but we should probably show some feedback about what's going on, then swap in the WebView once the page starts actually rendering? I also wonder if we could get away with just the context menu at first, then if someone wants to view the site they can?

It's the same behavior as long-pressing a URL anywhere in iOS.

> The new derived icons look great, though they make the Blog Root Screen look less nice 😅

Yeah, the header on the dashboard now looks ancient. I was thinking about replacing it with this new component in a separate PR. wdyt?

2024-07-25 17:03 UTC, jkmassel approved these changes

2024-07-25 17:20 UTC, merged