Add/application token management
wordpress-mobile/WordPress-iOS pull request #23492
Opened 2024-08-13 01:27 UTC by crazytonyli

There are two main changes in this PR:
1. The core of application-password authentication has been moved to wordpress-rs in https://github.com/Automattic/wordpress-rs/pull/250.
2. Add a logo to the new site address view, as suggested by @kean in https://github.com/wordpress-mobile/WordPress-iOS/pull/23484#pullrequestreview-2228512255.

## Screenshots

Please note: I didn't change this view to a modal, because that'll turn this login flow into modals on top of modals: site picker -> typing address -> web view to authenticate.

| Enter | Typing | Start login |
| - | - | - |
| <img width="556" alt="Screenshot 2024-08-13 at 1 18 57 PM" src="https://github.com/user-attachments/assets/e739950a-4b4f-4e0b-9cd7-4250f5fa649a"> | <img width="556" alt="Screenshot 2024-08-13 at 1 19 09 PM" src="https://github.com/user-attachments/assets/249cabde-aecf-497a-bbb6-5733dff8412a"> | <img width="556" alt="Screenshot 2024-08-13 at 1 19 12 PM" src="https://github.com/user-attachments/assets/eecff9f8-8ea1-4bfe-8d02-238a960d2edf"> |

## Regression Notes
1. Potential unintended areas of impact
None.

2. What I did to test those areas of impact (or what existing automated tests I relied on)
Verify login flow continues to work

3. What automated tests I added (or what prevented me from doing so)
None.

PR submission checklist:

- [x] I have completed the Regression Notes.
- [x] I have considered adding unit tests for my changes.
- [x] I have considered adding accessibility improvements for my changes.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

Testing checklist:
- [ ] WordPress.com sites and self-hosted Jetpack sites.
- [ ] Portrait and landscape orientations.
- [ ] Light and dark modes.
- [ ] Fonts: Larger, smaller and bold text.
- [ ] High contrast.
- [ ] VoiceOver.
- [ ] Languages with large words or with letters/accents not frequently used in English.
- [ ] Right-to-left languages. (Even if translation isn’t complete, formatting should still respect the right-to-left layout)
- [ ] iPhone and iPad. 
- [ ] Multi-tasking: Split view and Slide over. (iPad)

2024-08-13 01:27 UTC, dangermattic commented
<!--
  0 Errors
  1 Warning: <code>Modules/Package.swift</c...
  0 Messages
  0 Markdowns
-->
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false"><code>Modules/Package.swift</code> was changed without updating its corresponding <code>Package.resolved</code>. Please resolve the Swift packages in Xcode.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_pr-check">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

2024-08-13 18:14 UTC, kean requested changes
Smoke test passed. I left a couple of comments.

2024-08-13 18:14 UTC, kean commented on WordPress/Classes/Login/LoginWithUrlView.swift
> +                button.buttonStyle(.bordered)
This button doesn't look quite right. I suggest using the existing `DSButton` for now until there is a better replacement.

```swift
DSButton(title: SharedStrings.Button.continue, style: DSButtonStyle(emphasis: .primary, size: .large), isLoading: isLoading) {
    // TODO: handle action
}
.disabled(isContinueButtonDisabled)
```

 A better replacement should be implemented using native `ButtonStyle` API so you could use it as a modifier. I added the following type recently but it doesn't support the full-width presentation yet:

```swift
public struct PrimaryButtonStyle: ButtonStyle {
```

2024-08-13 18:14 UTC, kean commented on WordPress/Classes/Login/LoginWithUrlView.swift
> +    private func buttonContent() -> some View {
Unused code.

2024-08-13 18:14 UTC, kean commented on WordPress/Classes/Login/LoginWithUrlView.swift
>              .overlay(Divider(), alignment: .bottom)
The underline is too far from the view and looks like a separate divider. It was the case in the previous implementation also.

2024-08-13 18:14 UTC, kean commented on WordPress/Classes/Login/LoginWithUrlView.swift
> +            VStack(alignment: .center, spacing: 16) {
(nit) The `body` is getting too long. I would suggest extracting something.

2024-08-13 18:14 UTC, kean commented on WordPress/Classes/Login/LoginWithUrlView.swift
> +extension LoginWithUrlView {
Please make it `private`.

I think I like this approach more than `Strings`, but just noting that it's non-standard.

2024-08-13 21:00 UTC, crazytonyli commented
@kean Thanks for the view. I have addressed your comments in the commits above ⬆️ .

2024-08-13 22:40 UTC, kean commented
The changes look good. I would appreciate if you could hold off merging until https://github.com/wordpress-mobile/WordPress-iOS/pull/23498 is merged.

2024-08-14 17:26 UTC, kean approved these changes

2024-08-14 22:16 UTC, jkmassel approved these changes
LGTM – I think we can further improve on this but it's a great start!!

2024-08-15 22:25 UTC, merged